export type PagePatternKind = "topology" | "widget" | "background" | "adapter" | "card-grammar" | "instrument";

export type PagePattern = {
  id: string;
  label: string;
  kind: PagePatternKind;
  description: string;
  sourcePage: string;
  scope: "global" | "domain" | "branch" | "page";
  component?: string;
  parameters: string[];
};

/**
 * Reusable page grammars extracted from finished pages.
 * Knowledge Studio can surface this registry without coupling recipes to a
 * specific renderer implementation.
 */
export const PAGE_PATTERN_LIBRARY: PagePattern[] = [
  {
    id: "branching-tree-topology",
    label: "Branching tree",
    kind: "topology",
    description: "A recursive hierarchy for ancestry, dependencies, prerequisites, or any structure where forks matter more than a flat list.",
    sourcePage: "/natural-science/biology/zoology/diversity",
    scope: "global",
    component: "BranchingTreeTopology",
    parameters: ["root", "maxDepth", "selectedId", "pinnedIds", "onSelect", "onPin"],
  },
  {
    id: "taxonomic-path-widget",
    label: "Parallel rank path",
    kind: "widget",
    description: "Shows one or two hierarchical paths with explicit rank labels so parallel branches can be compared without flattening ancestry.",
    sourcePage: "/natural-science/biology/zoology/diversity",
    scope: "global",
    component: "TaxonomicPath",
    parameters: ["primary", "secondary"],
  },
  {
    id: "phylogenetic-canopy-background",
    label: "Phylogenetic canopy",
    kind: "background",
    description: "A vivid branching field where roots imply older ancestry, forks imply divergence, and pulses travel toward living tips.",
    sourcePage: "/natural-science/biology/zoology/diversity",
    scope: "domain",
    component: "PhylogeneticCanopyBackground",
    parameters: ["accentRgb"],
  },
  {
    id: "synchronized-comparison-topology",
    label: "Synchronized comparison",
    kind: "topology",
    description: "Runs several specimens or systems on one shared phase so differences in implementation stay aligned around the same functional question.",
    sourcePage: "/natural-science/biology/zoology/comparative",
    scope: "global",
    component: "SynchronizedComparisonTopology",
    parameters: ["specimens", "phase", "functionLabel", "selectedId", "onSelect"],
  },
  {
    id: "trait-matrix-widget",
    label: "Trait matrix",
    kind: "widget",
    description: "A compact row-aligned comparison matrix that shares column identities and semantic colors with a visual comparison surface.",
    sourcePage: "/natural-science/biology/zoology/comparative",
    scope: "global",
    component: "TraitMatrix",
    parameters: ["columns", "rows", "accentByColumn"],
  },
  {
    id: "anatomical-layer-background",
    label: "Anatomical layer field",
    kind: "background",
    description: "Translucent body silhouettes, scanning bands, and synchronized system pulses make parallel internal structures part of the page environment.",
    sourcePage: "/natural-science/biology/zoology/comparative",
    scope: "domain",
    component: "AnatomicalLayerBackground",
    parameters: ["accentRgb"],
  },
  {
    id: "behavior-sequence-topology",
    label: "Behavior sequence",
    kind: "topology",
    description: "A time-indexed causal sequence for stimulus, state, action, consequence, feedback, actors, and signals.",
    sourcePage: "/natural-science/biology/zoology/ethology",
    scope: "global",
    component: "BehaviorSequenceTopology",
    parameters: ["events", "duration", "currentTime", "selectedId", "onSelect"],
  },
  {
    id: "ethogram-widget",
    label: "Ethogram",
    kind: "widget",
    description: "A learner-editable observation table for assigning behavior codes and checking repeatable classification against recorded evidence.",
    sourcePage: "/natural-science/biology/zoology/ethology",
    scope: "global",
    component: "Ethogram",
    parameters: ["entries", "codes", "assignments", "onAssign"],
  },
  {
    id: "field-trace-background",
    label: "Field trace environment",
    kind: "background",
    description: "A nocturnal field layer of tracks, propagating calls, motion paths, and social-signal rings that makes behavior visible as evidence over time.",
    sourcePage: "/natural-science/biology/zoology/ethology",
    scope: "domain",
    component: "FieldTraceBackground",
    parameters: ["accentRgb"],
  },
  {
    id: "temporal-scale-topology",
    label: "Temporal scale navigator",
    kind: "topology",
    description: "A zoomable linear time window that preserves duration honestly while allowing different historical or scientific scales to become legible.",
    sourcePage: "/humanities/history/chronology",
    scope: "global",
    component: "TemporalScaleTopology",
    parameters: ["bands", "windows", "initialWindowId"],
  },
  {
    id: "chronology-river-background",
    label: "Chronology river",
    kind: "background",
    description: "Layered flowing temporal threads that evoke accumulated change without pretending history follows one single line.",
    sourcePage: "/humanities/history/chronology",
    scope: "domain",
    component: "ChronologyRiverBackground",
    parameters: [],
  },
  {
    id: "causation-check-widget",
    label: "Causation check",
    kind: "widget",
    description: "A compact claim-strength instrument that separates chronological order from mechanism, evidence, and competing explanations.",
    sourcePage: "/humanities/history/chronology",
    scope: "global",
    component: "CausationCheck",
    parameters: ["cause", "outcome"],
  },
  {
    id: "resource-flow-topology",
    label: "Resource flow system",
    kind: "topology",
    description: "A network of actors and reciprocal flows that can be read through multiple scales or analytical modes without changing the underlying system.",
    sourcePage: "/social-science/economics",
    scope: "global",
    component: "ResourceFlowTopology",
    parameters: [],
  },
  {
    id: "curve-shift-instrument",
    label: "Curve shift lab",
    kind: "instrument",
    description: "A reusable two-relationship graph where parameter shifts move entire curves and update an equilibrium or intersection in real time.",
    sourcePage: "/social-science/economics",
    scope: "global",
    component: "CurveShiftLab",
    parameters: [],
  },
  {
    id: "market-flow-background",
    label: "Market flow field",
    kind: "background",
    description: "Animated streams and exchange nodes make circulation and feedback visible as the page environment rather than decorative finance imagery.",
    sourcePage: "/social-science/economics",
    scope: "domain",
    component: "MarketFlowBackground",
    parameters: [],
  },
  {
    id: "logarithmic-scale-topology",
    label: "Logarithmic scale navigator",
    kind: "topology",
    description: "Places concepts or objects along powers of ten so jumps in physical scale remain intuitive instead of being flattened into equal cards.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "CosmicScaleTopology",
    parameters: ["nodes"],
  },
  {
    id: "deep-field-background",
    label: "Deep field",
    kind: "background",
    description: "A vivid layered star field with large-scale structure cues suitable for astronomy and other spatial-scale pages.",
    sourcePage: "/natural-science/astronomy",
    scope: "domain",
    component: "DeepFieldBackground",
    parameters: [],
  },
  {
    id: "method-lens-widget",
    label: "Method lens",
    kind: "widget",
    description: "Separates what is being studied from how evidence is obtained by toggling between complementary analytical methods.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "MethodLens",
    parameters: [],
  },
  {
    id: "light-travel-time-widget",
    label: "Signal travel-time viewer",
    kind: "widget",
    description: "Connects distance to information delay and lookback time through selectable source-observer examples.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "LightTravelTime",
    parameters: ["examples"],
  },
];
