import { animalSeed, type AnimalSeed } from "./zoology-types";
const s = animalSeed;
export const SPECIES_B: AnimalSeed[] = [
  s({commonName:"Polar bear",scientificName:"Ursus maritimus",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Ursidae",habitats:["Sea ice","Polar coasts"],regions:["Arctic"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"cathemeral",traits:["Marine mammal","Insulation","Long-distance swimmer"],summary:"An Arctic bear whose hunting ecology depends on sea ice and marine prey."}),
  s({commonName:"Arctic fox",scientificName:"Vulpes lagopus",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Canidae",habitats:["Tundra","Polar coasts"],regions:["Arctic"],diet:"omnivore",ecologicalRoles:["Mesopredator","Scavenger"],activity:"cathemeral",traits:["Seasonal coat","Food caching"],summary:"A small canid adapted to cold, seasonal scarcity, and rapidly changing food sources."}),
  s({commonName:"Snowy owl",scientificName:"Bubo scandiacus",phylum:"Chordata",className:"Aves",order:"Strigiformes",family:"Strigidae",habitats:["Tundra"],regions:["Arctic","Northern temperate zones"],diet:"carnivore",ecologicalRoles:["Mesopredator"],activity:"diurnal",traits:["Ground nesting","Irruptive migration"],summary:"A tundra owl whose movements track cycles in small-mammal abundance."}),
  s({commonName:"Walrus",scientificName:"Odobenus rosmarus",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Odobenidae",habitats:["Sea ice","Shallow seas"],regions:["Arctic"],diet:"carnivore",ecologicalRoles:["Benthic predator"],activity:"cathemeral",traits:["Tusks","Sensitive whiskers","Social haul-outs"],summary:"A large pinniped that searches seafloors for invertebrates using sensitive whiskers."}),
  s({commonName:"Emperor penguin",scientificName:"Aptenodytes forsteri",phylum:"Chordata",className:"Aves",order:"Sphenisciformes",family:"Spheniscidae",habitats:["Sea ice","Southern Ocean"],regions:["Antarctica"],diet:"carnivore",ecologicalRoles:["Marine predator"],activity:"diurnal",traits:["Deep diving","Huddling","Male incubation"],summary:"The largest penguin, breeding through Antarctic winter and diving beneath sea ice."}),
  s({commonName:"Orca",scientificName:"Orcinus orca",phylum:"Chordata",className:"Mammalia",order:"Artiodactyla",family:"Delphinidae",habitats:["Open ocean","Coastal waters"],regions:["Worldwide"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"cathemeral",traits:["Matrilineal pods","Cultural hunting traditions"],summary:"A globally distributed dolphin whose populations develop distinct diets and traditions."}),
  s({commonName:"Great white shark",scientificName:"Carcharodon carcharias",phylum:"Chordata",className:"Chondrichthyes",order:"Lamniformes",family:"Lamnidae",habitats:["Open ocean","Coastal waters"],regions:["Temperate oceans"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"variable",traits:["Regional endothermy","Long migration"],summary:"A large lamnid shark that migrates across ocean basins and hunts with sensory precision."}),
  s({commonName:"Blue whale",scientificName:"Balaenoptera musculus",phylum:"Chordata",className:"Mammalia",order:"Artiodactyla",family:"Balaenopteridae",habitats:["Open ocean"],regions:["Worldwide"],diet:"filter feeder",ecologicalRoles:["Nutrient transporter"],activity:"variable",traits:["Largest known animal","Baleen","Low-frequency song"],summary:"The largest known animal, filtering immense krill swarms and moving nutrients across oceans."}),
  s({commonName:"Giant Pacific octopus",scientificName:"Enteroctopus dofleini",phylum:"Mollusca",className:"Cephalopoda",order:"Octopoda",family:"Enteroctopodidae",habitats:["Rocky coast","Continental shelf"],regions:["North Pacific"],diet:"carnivore",ecologicalRoles:["Benthic predator"],activity:"nocturnal",traits:["Camouflage","Problem solving","Eight arms"],summary:"A large intelligent cephalopod with flexible behavior, camouflage, and a short life cycle."}),
  s({commonName:"Giant manta ray",scientificName:"Mobula birostris",phylum:"Chordata",className:"Chondrichthyes",order:"Myliobatiformes",family:"Mobulidae",habitats:["Open ocean","Reefs"],regions:["Tropical and subtropical oceans"],diet:"filter feeder",ecologicalRoles:["Planktivore"],activity:"diurnal",traits:["Cephalic fins","Long migration"],summary:"A giant filter-feeding ray that follows plankton blooms and visits cleaning stations."}),
  s({commonName:"Nile crocodile",scientificName:"Crocodylus niloticus",phylum:"Chordata",className:"Reptilia",order:"Crocodylia",family:"Crocodylidae",habitats:["Wetlands","Rivers","Lakes"],regions:["Sub-Saharan Africa"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"cathemeral",traits:["Ambush hunter","Parental care"],summary:"A large crocodilian shaping river and wetland food webs through ambush predation."}),
  s({commonName:"Hippopotamus",scientificName:"Hippopotamus amphibius",phylum:"Chordata",className:"Mammalia",order:"Artiodactyla",family:"Hippopotamidae",habitats:["Rivers","Wetlands","Grasslands"],regions:["Sub-Saharan Africa"],diet:"herbivore",ecologicalRoles:["Nutrient transporter","Ecosystem engineer"],activity:"nocturnal",traits:["Semi-aquatic","Territorial"],summary:"A massive grazer that feeds on land and transfers organic matter into freshwater systems."}),
  s({commonName:"Shoebill",scientificName:"Balaeniceps rex",phylum:"Chordata",className:"Aves",order:"Pelecaniformes",family:"Balaenicipitidae",habitats:["Papyrus swamps","Wetlands"],regions:["East-Central Africa"],diet:"carnivore",ecologicalRoles:["Wetland predator"],activity:"diurnal",traits:["Motionless hunting","Huge bill"],summary:"A towering swamp bird specialized for lungfish and other aquatic prey."}),
  s({commonName:"North American beaver",scientificName:"Castor canadensis",phylum:"Chordata",className:"Mammalia",order:"Rodentia",family:"Castoridae",habitats:["Rivers","Ponds","Wetlands"],regions:["North America"],diet:"herbivore",ecologicalRoles:["Ecosystem engineer"],activity:"nocturnal",traits:["Dam building","Tree felling"],summary:"A rodent whose dams create ponds, slow water, trap sediment, and expand wetland habitat."}),
  s({commonName:"American alligator",scientificName:"Alligator mississippiensis",phylum:"Chordata",className:"Reptilia",order:"Crocodylia",family:"Alligatoridae",habitats:["Wetlands","Rivers"],regions:["Southeastern United States"],diet:"carnivore",ecologicalRoles:["Apex predator","Ecosystem engineer"],activity:"cathemeral",traits:["Alligator holes","Parental care"],summary:"A crocodilian whose dry-season pools provide refuge for many wetland species."}),
  s({commonName:"Snow leopard",scientificName:"Panthera uncia",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Felidae",habitats:["Alpine","Rocky steppe"],regions:["Central Asia"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"crepuscular",traits:["Long tail","Wide paws","Dense coat"],summary:"A mountain cat adapted to cold, cliffs, and widely dispersed prey."}),
];
