import { animalSeed, type AnimalSeed } from "./zoology-types";
const s = animalSeed;
export const SPECIES_A: AnimalSeed[] = [
  s({commonName:"Jaguar",scientificName:"Panthera onca",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Felidae",habitats:["Tropical rainforest","Wetlands"],regions:["Central America","South America"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"crepuscular",traits:["Ambush hunter","Powerful bite","Strong swimmer"],summary:"A large spotted cat linking forest, river, and wetland food webs across the Americas."}),
  s({commonName:"Harpy eagle",scientificName:"Harpia harpyja",phylum:"Chordata",className:"Aves",order:"Accipitriformes",family:"Accipitridae",habitats:["Tropical rainforest"],regions:["Central America","South America"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"diurnal",traits:["Canopy hunter","Massive talons"],summary:"A giant forest eagle specialized for hunting mammals high in tropical canopies."}),
  s({commonName:"Dyeing poison dart frog",scientificName:"Dendrobates tinctorius",phylum:"Chordata",className:"Amphibia",order:"Anura",family:"Dendrobatidae",habitats:["Tropical rainforest"],regions:["Guiana Shield"],diet:"insectivore",ecologicalRoles:["Mesopredator"],activity:"diurnal",traits:["Warning color","Skin toxins","Parental care"],summary:"A brightly colored frog whose warning pattern advertises chemical defenses."}),
  s({commonName:"Capybara",scientificName:"Hydrochoerus hydrochaeris",phylum:"Chordata",className:"Mammalia",order:"Rodentia",family:"Caviidae",habitats:["Wetlands","Grasslands","Tropical rainforest"],regions:["South America"],diet:"herbivore",ecologicalRoles:["Grazer","Prey species"],activity:"crepuscular",traits:["Semi-aquatic","Social","Largest living rodent"],summary:"A social semi-aquatic grazer that moves nutrients between land and water."}),
  s({commonName:"Green anaconda",scientificName:"Eunectes murinus",phylum:"Chordata",className:"Reptilia",order:"Squamata",family:"Boidae",habitats:["Wetlands","Tropical rainforest"],regions:["South America"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"cathemeral",traits:["Constriction","Semi-aquatic"],summary:"A giant boa adapted to slow rivers, flooded forests, and ambush hunting in water."}),
  s({commonName:"Brown-throated sloth",scientificName:"Bradypus variegatus",phylum:"Chordata",className:"Mammalia",order:"Pilosa",family:"Bradypodidae",habitats:["Tropical rainforest"],regions:["Central America","South America"],diet:"herbivore",ecologicalRoles:["Canopy browser"],activity:"cathemeral",traits:["Suspensory locomotion","Slow metabolism"],summary:"A canopy specialist whose low-energy lifestyle supports a community in its fur."}),
  s({commonName:"Lion",scientificName:"Panthera leo",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Felidae",habitats:["Savanna","Grasslands"],regions:["Sub-Saharan Africa","India"],diet:"carnivore",ecologicalRoles:["Apex predator"],activity:"crepuscular",traits:["Pride society","Cooperative hunting"],summary:"A social big cat whose prides coordinate territory defense, hunting, and cub care."}),
  s({commonName:"African bush elephant",scientificName:"Loxodonta africana",phylum:"Chordata",className:"Mammalia",order:"Proboscidea",family:"Elephantidae",habitats:["Savanna","Grasslands","Woodlands"],regions:["Sub-Saharan Africa"],diet:"herbivore",ecologicalRoles:["Ecosystem engineer","Seed disperser"],activity:"cathemeral",traits:["Matriarchal herds","Landscape engineering"],summary:"The largest living land animal, reshaping vegetation, water access, and migration corridors."}),
  s({commonName:"Cheetah",scientificName:"Acinonyx jubatus",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Felidae",habitats:["Savanna","Grasslands"],regions:["Africa","Iran"],diet:"carnivore",ecologicalRoles:["Mesopredator"],activity:"diurnal",traits:["Sprint specialist","Flexible spine"],summary:"A pursuit predator built for short explosive chases across open ground."}),
  s({commonName:"Giraffe",scientificName:"Giraffa camelopardalis",phylum:"Chordata",className:"Mammalia",order:"Artiodactyla",family:"Giraffidae",habitats:["Savanna","Woodlands"],regions:["Sub-Saharan Africa"],diet:"herbivore",ecologicalRoles:["High browser","Seed disperser"],activity:"diurnal",traits:["Elongated neck","Ossicones"],summary:"A high browser whose extreme height opens a feeding niche above other herbivores."}),
  s({commonName:"Plains zebra",scientificName:"Equus quagga",phylum:"Chordata",className:"Mammalia",order:"Perissodactyla",family:"Equidae",habitats:["Savanna","Grasslands"],regions:["Eastern Africa","Southern Africa"],diet:"herbivore",ecologicalRoles:["Grazer","Prey species"],activity:"diurnal",traits:["Herding","Migration"],summary:"A migratory grazer whose herds track seasonal grass and water across African plains."}),
  s({commonName:"Spotted hyena",scientificName:"Crocuta crocuta",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Hyaenidae",habitats:["Savanna","Grasslands"],regions:["Sub-Saharan Africa"],diet:"carnivore",ecologicalRoles:["Apex predator","Scavenger"],activity:"nocturnal",traits:["Matriarchal clans","Bone-crushing jaws"],summary:"A social hunter and scavenger with complex clans and exceptional feeding flexibility."}),
  s({commonName:"Fennec fox",scientificName:"Vulpes zerda",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Canidae",habitats:["Desert"],regions:["North Africa","Sinai Peninsula"],diet:"omnivore",ecologicalRoles:["Mesopredator"],activity:"nocturnal",traits:["Oversized ears","Fur-covered feet"],summary:"A tiny desert fox that loses heat through its ears and finds prey beneath sand."}),
  s({commonName:"Dromedary",scientificName:"Camelus dromedarius",phylum:"Chordata",className:"Mammalia",order:"Artiodactyla",family:"Camelidae",habitats:["Desert","Arid scrub"],regions:["North Africa","Middle East"],diet:"herbivore",ecologicalRoles:["Browser"],activity:"diurnal",traits:["Fat-storing hump","Dehydration tolerance"],summary:"A one-humped camel adapted to large swings in temperature, hydration, and food quality."}),
  s({commonName:"Gila monster",scientificName:"Heloderma suspectum",phylum:"Chordata",className:"Reptilia",order:"Squamata",family:"Helodermatidae",habitats:["Desert"],regions:["Southwestern United States","Mexico"],diet:"carnivore",ecologicalRoles:["Mesopredator"],activity:"crepuscular",traits:["Venomous bite","Fat-storing tail"],summary:"A heavy-bodied venomous lizard that spends most of the year sheltered underground."}),
  s({commonName:"Meerkat",scientificName:"Suricata suricatta",phylum:"Chordata",className:"Mammalia",order:"Carnivora",family:"Herpestidae",habitats:["Desert","Dry grasslands"],regions:["Southern Africa"],diet:"omnivore",ecologicalRoles:["Mesopredator"],activity:"diurnal",traits:["Sentinel behavior","Cooperative breeding"],summary:"A cooperative mongoose whose groups divide labor among foraging, babysitting, and vigilance."}),
];
