import type { ZoologyCollection, ZoologyLensDefinition } from "./zoology-types";

export const ZOOLOGY_LENSES: ZoologyLensDefinition[] = [
  { id: "habitat", label: "By habitat", question: "Where can this body plan work?", description: "Compare animals shaped by the same physical environment.", icon: "Globe2" },
  { id: "lineage", label: "By lineage", question: "What does ancestry make possible?", description: "Follow inherited structures through different animal branches.", icon: "GitBranch" },
  { id: "ecology", label: "By ecology", question: "What job does the animal perform?", description: "Group species by role, interaction, and effect on a community.", icon: "Network" },
];

export const ZOOLOGY_COLLECTIONS: ZoologyCollection[] = [
  {id:"rainforest",lens:"habitat",label:"Tropical rainforest",question:"Who lives in a layered forest?",description:"Canopy, understory, river edge, and forest floor animals partition height, time, and food.",icon:"Trees",accentRgb:"52, 211, 153",environment:"canopy",speciesIds:["panthera-onca","harpia-harpyja","dendrobates-tinctorius","hydrochoerus-hydrochaeris","eunectes-murinus","bradypus-variegatus"]},
  {id:"savanna",lens:"habitat",label:"Savanna",question:"How does life follow grass and water?",description:"Seasonal rain, fire, migration, and large herbivores organize an open landscape.",icon:"Sun",accentRgb:"251, 191, 36",environment:"open",speciesIds:["panthera-leo","loxodonta-africana","acinonyx-jubatus","giraffa-camelopardalis","equus-quagga","crocuta-crocuta"]},
  {id:"desert",lens:"habitat",label:"Desert",question:"How do animals budget heat and water?",description:"Nocturnality, burrows, water conservation, and specialized locomotion solve scarcity.",icon:"ThermometerSun",accentRgb:"251, 146, 60",environment:"arid",speciesIds:["vulpes-zerda","camelus-dromedarius","heloderma-suspectum","suricata-suricatta"]},
  {id:"polar",lens:"habitat",label:"Polar worlds",question:"How does life persist around ice?",description:"Insulation, migration, huddling, and sea-ice access organize polar life.",icon:"Snowflake",accentRgb:"103, 232, 249",environment:"polar",speciesIds:["ursus-maritimus","vulpes-lagopus","bubo-scandiacus","odobenus-rosmarus","aptenodytes-forsteri"]},
  {id:"open-ocean",lens:"habitat",label:"Open ocean",question:"How do animals live without walls?",description:"Buoyancy, migration, depth, sound, and patchy food define a three-dimensional world.",icon:"Waves",accentRgb:"56, 189, 248",environment:"marine",speciesIds:["orcinus-orca","carcharodon-carcharias","balaenoptera-musculus","enteroctopus-dofleini","mobula-birostris"]},
  {id:"wetlands",lens:"habitat",label:"Wetlands",question:"What changes where land and water meet?",description:"Flooding, sediment, vegetation, and drought create dense ecological boundaries.",icon:"CloudFog",accentRgb:"45, 212, 191",environment:"wetland",speciesIds:["crocodylus-niloticus","hippopotamus-amphibius","balaeniceps-rex","castor-canadensis","alligator-mississippiensis","hydrochoerus-hydrochaeris"]},
  {id:"alpine",lens:"habitat",label:"Alpine",question:"How does life use steep, thin air?",description:"Cold, exposure, cliffs, and short growing seasons reward precise movement and energy use.",icon:"Mountain",accentRgb:"148, 163, 184",environment:"alpine",speciesIds:["panthera-uncia","aquila-chrysaetos","ochotona-princeps","oreamnos-americanus"]},
  {id:"temperate-forest",lens:"habitat",label:"Temperate forest",question:"How does seasonality reorganize a forest?",description:"Mast crops, leaf fall, hibernation, caching, and cavities change opportunity through the year.",icon:"Leaf",accentRgb:"34, 197, 94",environment:"forest",speciesIds:["vulpes-vulpes","ursus-americanus","dryocopus-pileatus","odocoileus-virginianus","myotis-lucifugus"]},
  {id:"coral-reef",lens:"habitat",label:"Coral reef",question:"How does diversity fit into a crowded structure?",description:"Reef architecture creates hiding places, feeding surfaces, cleaning stations, and partnerships.",icon:"Fish",accentRgb:"244, 114, 182",environment:"reef",speciesIds:["amphiprion-ocellaris","scarus-coeruleus","chelonia-mydas","carcharhinus-melanopterus","tridacna-gigas","labroides-dimidiatus"]},

  {id:"mammals",lens:"lineage",label:"Mammals",question:"What can one inherited body plan become?",description:"Hair, milk, endothermy, and shared jaw history diversify into runners, swimmers, fliers, and diggers.",icon:"PawPrint",accentRgb:"248, 113, 113",environment:"taxonomy",speciesIds:["panthera-onca","loxodonta-africana","balaenoptera-musculus","ornithorhynchus-anatinus","myotis-lucifugus","hydrochoerus-hydrochaeris"]},
  {id:"birds",lens:"lineage",label:"Birds",question:"How does a dinosaur lineage fill the sky and beyond?",description:"Feathers, air sacs, eggs, and lightweight skeletons support flight, diving, running, and polar endurance.",icon:"Bird",accentRgb:"250, 204, 21",environment:"taxonomy",speciesIds:["harpia-harpyja","bubo-scandiacus","balaeniceps-rex","aquila-chrysaetos","aptenodytes-forsteri","archilochus-colubris"]},
  {id:"reptiles",lens:"lineage",label:"Reptiles",question:"How do scales, eggs, and temperature shape a lineage?",description:"Reptiles solve water balance, incubation, and predation across deserts, rivers, forests, and seas.",icon:"Shell",accentRgb:"74, 222, 128",environment:"taxonomy",speciesIds:["eunectes-murinus","heloderma-suspectum","crocodylus-niloticus","alligator-mississippiensis","chelonia-mydas"]},
  {id:"amphibians",lens:"lineage",label:"Amphibians",question:"What happens when life crosses water and land?",description:"Permeable skin and flexible life cycles expose development and environmental sensitivity.",icon:"Droplets",accentRgb:"45, 212, 191",environment:"taxonomy",speciesIds:["dendrobates-tinctorius","ambystoma-mexicanum"]},
  {id:"invertebrates",lens:"lineage",label:"Invertebrates",question:"What lies beyond the vertebrate template?",description:"Most animal diversity lives here: exoskeletons, shells, distributed nervous systems, and unfamiliar life cycles.",icon:"Bug",accentRgb:"192, 132, 252",environment:"taxonomy",speciesIds:["enteroctopus-dofleini","tridacna-gigas","danaus-plexippus","apis-mellifera"]},

  {id:"apex-predators",lens:"ecology",label:"Apex predators",question:"What changes when few animals can hunt you?",description:"Top predators alter prey behavior, scavengers, population structure, and energy flow.",icon:"Crown",accentRgb:"248, 113, 113",environment:"network",speciesIds:["panthera-onca","panthera-leo","orcinus-orca","ursus-maritimus","carcharodon-carcharias","crocodylus-niloticus"]},
  {id:"ecosystem-engineers",lens:"ecology",label:"Ecosystem engineers",question:"Which animals physically rewrite habitat?",description:"Dams, burrows, grazing, tree damage, and sediment movement reorganize communities.",icon:"Hammer",accentRgb:"251, 191, 36",environment:"network",speciesIds:["loxodonta-africana","castor-canadensis","alligator-mississippiensis","scarus-coeruleus","cynomys-ludovicianus","dryocopus-pileatus"]},
  {id:"animal-societies",lens:"ecology",label:"Animal societies",question:"What can coordinated groups do?",description:"Communication, memory, division of labor, cooperation, and conflict produce social systems.",icon:"Users",accentRgb:"167, 139, 250",environment:"network",speciesIds:["panthera-leo","loxodonta-africana","suricata-suricatta","orcinus-orca","apis-mellifera","cynomys-ludovicianus"]},
  {id:"mutualisms",lens:"ecology",label:"Mutualisms",question:"When does another species become part of the solution?",description:"Protection, cleaning, nutrition, and transport can be exchanged across species boundaries.",icon:"HeartHandshake",accentRgb:"52, 211, 153",environment:"network",speciesIds:["amphiprion-ocellaris","tridacna-gigas","buphagus-erythrorynchus","labroides-dimidiatus"]},
  {id:"pollinators",lens:"ecology",label:"Pollinators",question:"How does animal movement become plant reproduction?",description:"Nectar, pollen, color, scent, timing, and memory connect foraging to plant gene flow.",icon:"Flower2",accentRgb:"244, 114, 182",environment:"network",speciesIds:["apis-mellifera","danaus-plexippus","archilochus-colubris","myotis-lucifugus"]},
  {id:"herbivores",lens:"ecology",label:"Herbivores",question:"How do animals solve the problem of eating plants?",description:"Teeth, guts, microbes, migration, browsing height, and defense turn plants into animal energy.",icon:"Leaf",accentRgb:"132, 204, 22",environment:"network",speciesIds:["loxodonta-africana","giraffa-camelopardalis","equus-quagga","hydrochoerus-hydrochaeris","bradypus-variegatus","chelonia-mydas"]},
];
