"use client";
import React from "react";
import Link from "next/link";
import LorenzAttractor from "./LorenzAttractor";
import { ArrowLeft, Zap, GitFork, Tornado, Infinity as InfinityIcon } from "lucide-react";
import SystemsBackground from "./SystemsBackground";

export default function ChaosTheoryPage() {
  return (
    <main className="min-h-screen bg-[#050202] text-red-100 font-sans relative overflow-hidden selection:bg-red-500/30">
      
      {/* 1. SHARED ATMOSPHERE */}
      <SystemsBackground />
      <div className="fixed inset-0 bg-gradient-to-b from-[#050202] via-transparent to-[#050202] pointer-events-none" />

      <div className="relative z-10 p-6 md:p-12 min-h-screen flex flex-col">
        
        {/* HEADER */}
        <header className="mb-12">
            <Link href="/formal-science/systems-science" className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-red-600 hover:text-white transition-colors mb-6">
                <ArrowLeft size={10} /> Systems Science
            </Link>
            <h1 className="text-5xl md:text-7xl font-black text-white tracking-tighter mb-4 flex items-center gap-4">
                CHAOS THEORY <Tornado className="text-red-600 opacity-80 animate-spin-slow" size={48} />
            </h1>
            <p className="text-red-400/60 font-mono text-xs uppercase tracking-widest max-w-xl">
                Deterministic Chaos // Nonlinear Dynamics // Sensitive Dependence
            </p>
        </header>

        {/* 2. HERO: THE LORENZ ATTRACTOR */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-16">
            <div className="lg:col-span-2">
                <LorenzAttractor />
            </div>
            <div className="flex flex-col justify-center gap-6 p-6 rounded-xl bg-black/40 border border-red-900/20 backdrop-blur-sm">
                <div>
                    <h3 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
                        <GitFork size={18} className="text-red-500" /> Sensitive Dependence
                    </h3>
                    <p className="text-sm text-red-200/60 leading-relaxed">
                        Often called the <strong>Butterfly Effect</strong>. In nonlinear systems, a tiny difference in starting conditions (like the flap of a butterfly's wings) can lead to vastly different outcomes (like a tornado weeks later).
                    </p>
                </div>
                
                <div className="w-full h-px bg-red-900/30" />

                <div>
                    <h3 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
                        <InfinityIcon size={18} className="text-red-500" /> Strange Attractors
                    </h3>
                    <p className="text-sm text-red-200/60 leading-relaxed">
                        Despite being unpredictable in the moment, chaotic systems often settle into a distinct shape or pattern over time. The Lorenz Attractor (left) is a "Strange Attractor"—the system orbits these two loops forever, never crossing the same path twice.
                    </p>
                </div>
            </div>
        </div>

        {/* 3. CORE CONCEPTS GRID */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pb-20">
            
            {/* CARD 1: DETERMINISM */}
            <div className="p-6 rounded-xl bg-black/40 border border-red-900/20 hover:border-red-500/50 transition-all">
                <div className="text-[10px] font-bold uppercase tracking-widest text-red-600 mb-2">Misconception</div>
                <h3 className="text-xl font-bold text-white mb-2">Chaos ≠ Randomness</h3>
                <p className="text-xs text-red-200/50 leading-relaxed mb-4">
                    Chaotic systems are <em>deterministic</em>. They follow strict laws of physics (no dice rolling). They only <em>appear</em> random because we cannot measure the current state with infinite precision.
                </p>
            </div>

            {/* CARD 2: FRACTALS */}
            <div className="p-6 rounded-xl bg-black/40 border border-red-900/20 hover:border-red-500/50 transition-all group">
                <div className="text-[10px] font-bold uppercase tracking-widest text-red-600 mb-2">Geometry</div>
                <h3 className="text-xl font-bold text-white mb-2">Fractals</h3>
                <p className="text-xs text-red-200/50 leading-relaxed mb-4">
                    Chaos often leaves a visual footprint called a fractal—shapes that look similar at any scale. Coastlines, clouds, and blood vessels are all fractal structures generated by chaotic growth processes.
                </p>
                
            </div>

             {/* CARD 3: BIFURCATION */}
             <div className="p-6 rounded-xl bg-black/40 border border-red-900/20 hover:border-red-500/50 transition-all">
                <div className="text-[10px] font-bold uppercase tracking-widest text-red-600 mb-2">Transition</div>
                <h3 className="text-xl font-bold text-white mb-2">Bifurcation</h3>
                <p className="text-xs text-red-200/50 leading-relaxed mb-4">
                    As you turn up the energy in a system (like turning up a faucet), it transitions from smooth flow (order) to dripping (periodicity) to splashing (chaos). This splitting point is a bifurcation.
                </p>
                
            </div>

        </div>

      </div>
    </main>
  );
}