import type { PagePattern } from "./types";

export const ACADEMIC_WORLD_PATTERNS_V2: PagePattern[] = [
  {
    id: "academic-world-contract",
    label: "Academic world contract",
    kind: "adapter",
    description: "Defines the environment metaphor, interaction metaphor, navigation grammar, and visual taboos that make one academic page structurally distinct from another.",
    sourcePage: "/studio/foundry",
    scope: "global",
    component: "AcademicWorldDefinition",
    parameters: ["id", "promise", "environmentMetaphor", "interactionMetaphor", "preferredTopologies", "avoid"],
  },
  {
    id: "exhibit-campus-topology",
    label: "Exhibit campus",
    kind: "topology",
    description: "Places direct curriculum children around a central shared exhibit so primary branches remain prominent without confusing the browsing surface for another peer route.",
    sourcePage: "/natural-science/biology/zoology",
    scope: "global",
    component: "ExhibitCampusTopology",
    parameters: ["title", "description", "centerLabel", "centerSummary", "destinations", "accentRgb"],
  },
  {
    id: "living-exhibit-background",
    label: "Living exhibit environment",
    kind: "background",
    description: "Combines a visible visitor trail, habitat strata, field signs, tracks, and environment-specific scenery into a coherent conservation-park setting.",
    sourcePage: "/natural-science/biology/zoology",
    scope: "global",
    component: "LivingExhibitBackground",
    parameters: ["accentRgb", "environment"],
  },
  {
    id: "expedition-route-topology",
    label: "Expedition route",
    kind: "topology",
    description: "Turns direct children into sequential or scale-aware waypoints while separating cross-cutting methods into a secondary instrument layer.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "ExpeditionRouteTopology",
    parameters: ["title", "description", "stops", "accentRgb"],
  },
  {
    id: "galactic-expedition-background",
    label: "Galactic expedition environment",
    kind: "background",
    description: "A mission-deck field of parallax stars, orbital scans, cosmic structure, and a persistent waypoint route rather than stars placed behind ordinary cards.",
    sourcePage: "/natural-science/astronomy",
    scope: "domain",
    component: "GalacticExpeditionBackground",
    parameters: [],
  },
];
