import type { PagePattern } from "./types";

export const CHEMISTRY_LINGUISTICS_PATTERNS: PagePattern[] = [
  {
    id: "parts-structure-process-topology",
    label: "Parts → structure → process",
    kind: "topology",
    description: "Moves between component inventory, organized structure, and transformation so learners change unit of analysis without losing the system relationship.",
    sourcePage: "/natural-science/chemistry",
    scope: "global",
    component: "PartsStructureProcessTopology",
    parameters: ["stages"],
  },
  {
    id: "molecular-reaction-background",
    label: "Molecular reaction field",
    kind: "background",
    description: "A vivid network of atoms, bonds, oscillating molecular clusters, and transformation streams for composition-and-reaction subjects.",
    sourcePage: "/natural-science/chemistry",
    scope: "domain",
    component: "MolecularReactionBackground",
    parameters: [],
  },
  {
    id: "periodic-table-instrument",
    label: "Periodic table explorer",
    kind: "instrument",
    description: "A property-coded periodic table that exposes element identity, group/family patterns, and selectable element detail.",
    sourcePage: "/natural-science/chemistry",
    scope: "branch",
    component: "PeriodicTable",
    parameters: ["activeZ", "onSelect"],
  },
  {
    id: "molecule-viewer-instrument",
    label: "Molecule viewer",
    kind: "instrument",
    description: "A molecular structure viewer for connecting composition, bonding, geometry, and emergent material properties.",
    sourcePage: "/natural-science/chemistry",
    scope: "branch",
    component: "MoleculeViewer",
    parameters: [],
  },
  {
    id: "reaction-balancer-instrument",
    label: "Reaction balancer",
    kind: "instrument",
    description: "An interactive equation-balancing surface that makes conservation of elements visible during chemical rearrangement.",
    sourcePage: "/natural-science/chemistry",
    scope: "global",
    component: "ReactionBalancer",
    parameters: [],
  },
  {
    id: "communication-loop-topology",
    label: "Communication loop",
    kind: "topology",
    description: "Organizes a system around recurring interaction among structure, individual processing, social context, learning, and long-term change.",
    sourcePage: "/social-science/linguistics",
    scope: "global",
    component: "CommunicationLoopTopology",
    parameters: ["stages"],
  },
  {
    id: "language-stack-topology",
    label: "Compositional stack",
    kind: "topology",
    description: "Shows increasingly large units of analysis as nested compositional layers while emphasizing that higher layers introduce new relationships.",
    sourcePage: "/social-science/linguistics/structure",
    scope: "global",
    component: "LanguageStackTopology",
    parameters: ["layers"],
  },
  {
    id: "language-signal-background",
    label: "Language signal field",
    kind: "background",
    description: "A layered signal environment mixing waveform bands, structural branches, and linguistic units from sound through context.",
    sourcePage: "/social-science/linguistics",
    scope: "domain",
    component: "LanguageSignalBackground",
    parameters: [],
  },
  {
    id: "syntax-tree-instrument",
    label: "Constituency tree lab",
    kind: "instrument",
    description: "An interactive hierarchical sentence tree with selectable and collapsible constituents for making non-linear syntactic structure visible.",
    sourcePage: "/social-science/linguistics/structure",
    scope: "global",
    component: "SyntaxTreeLab",
    parameters: [],
  },
];
