import type { PagePattern } from "./types";

export const MUSIC_PHILOSOPHY_PATTERNS: PagePattern[] = [
  {
    id: "mixing-console-topology",
    label: "Mixing console",
    kind: "topology",
    description: "Treats simultaneously active dimensions as parallel channels so each can be isolated for study without implying a false sequence or hierarchy.",
    sourcePage: "/humanities/music",
    scope: "global",
    component: "MixingConsoleTopology",
    parameters: ["channels"],
  },
  {
    id: "waveform-aurora-background",
    label: "Waveform aurora",
    kind: "background",
    description: "A high-contrast field of moving waveforms, spectral bars, and luminous color bands for sound, media, and signal-driven subjects.",
    sourcePage: "/humanities/music",
    scope: "domain",
    component: "WaveformAuroraBackground",
    parameters: [],
  },
  {
    id: "harmonic-lattice-background",
    label: "Harmonic lattice",
    kind: "background",
    description: "A connected pitch-like lattice with pulsing interval relationships for theory, harmony, and other cyclic relational structures.",
    sourcePage: "/humanities/music/theory",
    scope: "domain",
    component: "HarmonicLatticeBackground",
    parameters: [],
  },
  {
    id: "circle-of-fifths-instrument",
    label: "Circle of fifths",
    kind: "instrument",
    description: "An interactive cyclic pitch-class relationship viewer for key proximity, accidentals, and tonic-dominant-subdominant relationships.",
    sourcePage: "/humanities/music/theory",
    scope: "branch",
    component: "CircleOfFifthsLab",
    parameters: [],
  },
  {
    id: "media-shelf-topology",
    label: "Media shelf",
    kind: "topology",
    description: "A collection presentation that can switch between chronological shelves and a mosaic while retaining searchable rich records.",
    sourcePage: "/humanities/music/recordings",
    scope: "global",
    component: "MediaShelfTopology",
    parameters: ["records", "selectedId", "onSelect", "accentRgb"],
  },
  {
    id: "media-detail-drawer",
    label: "Media detail drawer",
    kind: "widget",
    description: "A generic rich-record drawer for creators, dates, tags, structured facts, media, attribution, and source links.",
    sourcePage: "/humanities/music/recordings",
    scope: "global",
    component: "MediaDetailDrawer",
    parameters: ["record", "accentRgb", "onClose"],
  },
  {
    id: "collection-media-record",
    label: "Collection media record",
    kind: "adapter",
    description: "A normalized record contract for albums, games, films, books, artifacts, and other searchable media collections.",
    sourcePage: "/humanities/music/recordings",
    scope: "global",
    component: "CollectionMediaRecord",
    parameters: ["id", "title", "creator", "year", "tags", "facts", "sources"],
  },
  {
    id: "musicbrainz-album-adapter",
    label: "MusicBrainz album adapter",
    kind: "adapter",
    description: "Normalizes MusicBrainz release groups and Cover Art Archive media into the shared collection record contract.",
    sourcePage: "/humanities/music/recordings",
    scope: "global",
    component: "api/music/albums",
    parameters: ["q"],
  },
  {
    id: "question-matrix-topology",
    label: "Question matrix",
    kind: "topology",
    description: "Positions overlapping fields by two semantic dimensions so neighboring questions remain visibly related without forcing a false hierarchy.",
    sourcePage: "/humanities/philosophy",
    scope: "global",
    component: "QuestionMatrixTopology",
    parameters: ["nodes", "xLabels", "yLabels"],
  },
  {
    id: "argument-map-widget",
    label: "Argument map",
    kind: "widget",
    description: "Separates question, claim, reasons, objections, and replies into inspectable nodes so disagreement can target the right part of an argument.",
    sourcePage: "/humanities/philosophy",
    scope: "global",
    component: "ArgumentMap",
    parameters: ["nodes"],
  },
  {
    id: "dialectic-field-background",
    label: "Dialectic field",
    kind: "background",
    description: "A layered environment of converging and diverging reasoning threads, claim nodes, and slow pulses for inquiry-centered pages.",
    sourcePage: "/humanities/philosophy",
    scope: "domain",
    component: "DialecticFieldBackground",
    parameters: [],
  },
];
