import type { PagePattern } from "./types";

export const TIME_ECONOMY_SPACE_PATTERNS: PagePattern[] = [
  {
    id: "temporal-scale-topology",
    label: "Temporal scale navigator",
    kind: "topology",
    description: "A zoomable linear time window that preserves duration honestly while allowing different historical or scientific scales to become legible.",
    sourcePage: "/humanities/history/chronology",
    scope: "global",
    component: "TemporalScaleTopology",
    parameters: ["bands", "windows", "initialWindowId"],
  },
  {
    id: "chronology-river-background",
    label: "Chronology river",
    kind: "background",
    description: "Layered flowing temporal threads that evoke accumulated change without pretending history follows one single line.",
    sourcePage: "/humanities/history/chronology",
    scope: "domain",
    component: "ChronologyRiverBackground",
    parameters: [],
  },
  {
    id: "causation-check-widget",
    label: "Causation check",
    kind: "widget",
    description: "A compact claim-strength instrument that separates chronological order from mechanism, evidence, and competing explanations.",
    sourcePage: "/humanities/history/chronology",
    scope: "global",
    component: "CausationCheck",
    parameters: ["cause", "outcome"],
  },
  {
    id: "resource-flow-topology",
    label: "Resource flow system",
    kind: "topology",
    description: "A network of actors and reciprocal flows that can be read through multiple scales or analytical modes without changing the underlying system.",
    sourcePage: "/social-science/economics",
    scope: "global",
    component: "ResourceFlowTopology",
    parameters: [],
  },
  {
    id: "curve-shift-instrument",
    label: "Curve shift lab",
    kind: "instrument",
    description: "A reusable two-relationship graph where parameter shifts move entire curves and update an equilibrium or intersection in real time.",
    sourcePage: "/social-science/economics",
    scope: "global",
    component: "CurveShiftLab",
    parameters: [],
  },
  {
    id: "market-flow-background",
    label: "Market flow field",
    kind: "background",
    description: "Animated streams and exchange nodes make circulation and feedback visible as the page environment rather than decorative finance imagery.",
    sourcePage: "/social-science/economics",
    scope: "domain",
    component: "MarketFlowBackground",
    parameters: [],
  },
  {
    id: "logarithmic-scale-topology",
    label: "Logarithmic scale navigator",
    kind: "topology",
    description: "Places concepts or objects along powers of ten so jumps in physical scale remain intuitive instead of being flattened into equal cards.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "CosmicScaleTopology",
    parameters: ["nodes"],
  },
  {
    id: "deep-field-background",
    label: "Deep field",
    kind: "background",
    description: "A vivid layered star field with large-scale structure cues suitable for astronomy and other spatial-scale pages.",
    sourcePage: "/natural-science/astronomy",
    scope: "domain",
    component: "DeepFieldBackground",
    parameters: [],
  },
  {
    id: "method-lens-widget",
    label: "Method lens",
    kind: "widget",
    description: "Separates what is being studied from how evidence is obtained by toggling between complementary analytical methods.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "MethodLens",
    parameters: [],
  },
  {
    id: "light-travel-time-widget",
    label: "Signal travel-time viewer",
    kind: "widget",
    description: "Connects distance to information delay and lookback time through selectable source-observer examples.",
    sourcePage: "/natural-science/astronomy",
    scope: "global",
    component: "LightTravelTime",
    parameters: ["examples"],
  },
];
