import type { PagePattern } from "./types";

export const VISUAL_ART_PATTERNS: PagePattern[] = [
  {
    id: "practice-studio-topology",
    label: "Practice studio",
    kind: "topology",
    description: "An asymmetric sibling-navigation surface for practices distinguished by medium, tool, or mode of making rather than a false hierarchy.",
    sourcePage: "/humanities/visual-arts",
    scope: "global",
    component: "PracticeStudioTopology",
    parameters: ["nodes"],
  },
  {
    id: "gallery-wall-topology",
    label: "Gallery wall",
    kind: "topology",
    description: "A media-first collection surface that can switch between an irregular salon wall and a metadata-oriented catalog list.",
    sourcePage: "/humanities/visual-arts",
    scope: "global",
    component: "GalleryWallTopology",
    parameters: ["records", "selectedId", "onSelect", "accentRgb"],
  },
  {
    id: "pigment-field-background",
    label: "Pigment field",
    kind: "background",
    description: "A vivid environment of drifting pigment washes, brush-like paths, speckled marks, and canvas-like spatial layering.",
    sourcePage: "/humanities/visual-arts",
    scope: "domain",
    component: "PigmentFieldBackground",
    parameters: [],
  },
  {
    id: "met-museum-adapter",
    label: "Met Museum adapter",
    kind: "adapter",
    description: "Normalizes Metropolitan Museum collection objects into the shared media-record contract with image, maker, date, medium, dimensions, department, and source metadata.",
    sourcePage: "/humanities/visual-arts",
    scope: "global",
    component: "api/art/met",
    parameters: ["q"],
  },
  {
    id: "composition-guide-instrument",
    label: "Composition guide lab",
    kind: "instrument",
    description: "Compares no guide, thirds, and golden-ratio overlays without treating any proportional system as a universal aesthetic law.",
    sourcePage: "/humanities/visual-arts",
    scope: "global",
    component: "GoldenRatioComposer",
    parameters: [],
  },
  {
    id: "color-relationship-instrument",
    label: "Color relationship lab",
    kind: "instrument",
    description: "Explores hue-wheel relationships while keeping saturation, lightness, area, and context distinct from simple hue geometry.",
    sourcePage: "/humanities/visual-arts",
    scope: "global",
    component: "ChromaEngine",
    parameters: [],
  },
];
