"use client";

import { useState } from "react";
import { Dna, Sparkles } from "lucide-react";
import Assessment, { type AssessmentQuestion } from "@/app/_components/Assessment";
import ClassroomLessonShell, { type ClassroomLessonNavItem } from "./ClassroomLessonShell";

type Props = { breadcrumbs: readonly { label: string; href?: string }[]; unitHref: string; previous?: ClassroomLessonNavItem; next?: ClassroomLessonNavItem };
type SampleId = "glucose" | "starch" | "cellulose";
const SAMPLES = {
  glucose: { name: "Glucose", form: "one portable ring", links: "no glycosidic links", access: "small enough for transport and metabolic pathways", role: "immediate fuel and building block", color: "#86efac" },
  starch: { name: "Starch", form: "coiled and branched α-glucose chains", links: "α linkages; many accessible ends", access: "enzymes can release glucose from many branch ends", role: "mobilizable energy storage in plants", color: "#facc15" },
  cellulose: { name: "Cellulose", form: "straight β-glucose chains", links: "β linkages align neighboring chains", access: "chains hydrogen-bond into tough fibers", role: "structural support in plant cell walls", color: "#67e8f9" },
} as const;
const QUIZ: AssessmentQuestion[] = [
  { id: "carb-arrangement", type: "mcq", prompt: "Starch and cellulose both contain glucose. Why do they behave differently?", options: ["Their glucose units are linked and arranged differently", "Cellulose contains no carbon", "Starch is made from amino acids"], correctAnswer: "Their glucose units are linked and arranged differently", explanation: "Different glycosidic linkages change chain geometry, enzyme access, and therefore function." },
  { id: "carb-branch", type: "mcq", prompt: "Which feature helps a storage polymer release glucose from several places?", options: ["Many branch ends", "Perfectly aligned fibers", "A single unlinked ring only"], correctAnswer: "Many branch ends", explanation: "Branching creates multiple ends where enzymes can work, supporting rapid mobilization." },
  { id: "carb-boundary", type: "mcq", prompt: "Which claim is too broad?", options: ["All carbohydrates are merely immediate fuel", "Some carbohydrates store energy", "Some carbohydrates provide structural support"], correctAnswer: "All carbohydrates are merely immediate fuel", explanation: "Carbohydrate function depends on structure; cellulose is structural and starch stores energy." },
];

export default function CarbohydratesLesson({ breadcrumbs, unitHref, previous, next }: Props) {
  const [sampleId, setSampleId] = useState<SampleId>("glucose");
  const [prediction, setPrediction] = useState<"starch" | "cellulose" | null>(null);
  const sample = SAMPLES[sampleId];
  return <ClassroomLessonShell subjectTone="science" breadcrumbs={breadcrumbs} eyebrow="AP Biology · Unit 1 · Topic 1.4" icon={Dna} title="Carbohydrates" subtitle="Change one glucose arrangement, then watch storage and structural function diverge." stages={["Notice","Link","Shape","Test","Transfer","Practice","Conclude"]} practiceTargetId="carb-practice" unitHref={unitHref} previous={previous} next={next} lessonPosition="04 / 07" background={<CarbohydrateField />}>
    <LessonSection number="1" label="Notice" title="Same pieces. Different material.">
      <p className="text-[15px] leading-6 text-stone-300">Glucose appears alone and inside both starch and cellulose. Composition starts the explanation, but arrangement finishes it.</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-3"><MoleculeSketch kind="glucose"/><MoleculeSketch kind="starch"/><MoleculeSketch kind="cellulose"/></div>
    </LessonSection>
    <LessonSection number="2" label="Link" title="A linkage changes the direction of the chain.">
      <div className="grid gap-3 lg:grid-cols-[0.9fr_1.1fr]"><p className="text-[15px] leading-7 text-stone-300">In this introductory model, α-linked glucose tends to form coiled or branched storage structures. β-linked glucose produces straight chains that align into fibers. The monomer stays glucose; the geometry changes.</p><div className="rounded-[16px] border border-green-200/15 bg-green-300/[0.05] p-4 font-mono text-[14px] text-green-50">linkage → chain shape → enzyme access / fiber strength → function</div></div>
    </LessonSection>
    <section className="mt-4 rounded-[22px] border border-green-200/15 bg-[#03150e]/75 p-4 backdrop-blur-2xl sm:p-5"><Stage number="3" label="Shape"/><h2 className="mt-1 text-2xl font-semibold text-white">Run the carbohydrate structure scanner.</h2>
      <div className="mt-4 flex flex-wrap gap-2">{(Object.keys(SAMPLES) as SampleId[]).map(id=><button key={id} onClick={()=>setSampleId(id)} aria-pressed={id===sampleId} className={`min-h-11 rounded-full border px-4 text-[14px] font-semibold ${id===sampleId?"border-green-200/40 bg-green-300/15 text-white":"border-white/10 bg-black/20 text-stone-400"}`}>{SAMPLES[id].name}</button>)}</div>
      <div className="mt-4 grid gap-3 md:grid-cols-[1.1fr_0.9fr]"><div className="rounded-[20px] border border-white/10 bg-black/20 p-5"><div className="flex min-h-56 items-center justify-center"><ChainDiagram kind={sampleId}/></div><p className="text-center font-mono text-[13px]" style={{color:sample.color}}>{sample.form}</p></div><dl className="grid gap-2"><Readout term="Link evidence" value={sample.links}/><Readout term="Consequence" value={sample.access}/><Readout term="Biological role" value={sample.role}/></dl></div>
    </section>
    <LessonSection number="4" label="Test" title="Test a composition-only explanation."><p className="text-[15px] leading-7 text-stone-300">“Cellulose and starch must have the same function because both contain glucose.” The premise is true; the conclusion fails because it ignores linkage, shape, and access.</p><div className="mt-3 rounded-[15px] border border-amber-200/20 bg-amber-300/[0.05] p-3 text-[14px] text-amber-50"><strong>Boundary:</strong> humans can digest starch but lack enzymes that hydrolyze cellulose’s β linkages. Cellulose still matters as dietary fiber.</div></LessonSection>
    <LessonSection number="5" label="Transfer" title="Which architecture fits a load-bearing tissue?"><p className="text-[15px] text-stone-300">A plant tissue must resist stretching while remaining thin. Choose the stronger prediction, then inspect the evidence boundary.</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{(["starch","cellulose"] as const).map(id=><button key={id} onClick={()=>setPrediction(id)} className={`rounded-[15px] border p-4 text-left ${prediction===id?"border-cyan-200/35 bg-cyan-300/10":"border-white/10 bg-black/15"}`}><strong className="text-white">{SAMPLES[id].name}</strong><span className="mt-1 block text-[13px] text-stone-400">{SAMPLES[id].form}</span></button>)}</div>{prediction&&<p role="status" className={`mt-3 rounded-[14px] border p-3 text-[14px] ${prediction==="cellulose"?"border-emerald-200/25 bg-emerald-300/10 text-emerald-50":"border-amber-200/25 bg-amber-300/10 text-amber-50"}`}>{prediction==="cellulose"?"Yes. Straight chains align and hydrogen-bond into load-bearing fibers.":"Revise: branching supports accessible storage, while aligned cellulose fibers support tension."}</p>}</LessonSection>
    <section id="carb-practice" className="mt-4"><Assessment title="Practice the structure → function chain" questions={QUIZ}/></section>
    <LessonSection number="7" label="Conclude" title="Function is structure in context."><div className="flex gap-3"><Sparkles className="mt-1 text-green-200" size={18}/><p className="text-[15px] leading-7 text-stone-300">When two biological molecules share building blocks, do not stop at composition. Trace linkage, shape, interaction, and access to explain what each structure can do.</p></div></LessonSection>
  </ClassroomLessonShell>;
}
function Stage({number,label}:{number:string;label:string}){return <p className="font-mono text-[11px] font-semibold uppercase tracking-[.14em] text-green-200/70">{number.padStart(2,"0")} · {label}</p>}
function LessonSection({number,label,title,children}:{number:string;label:string;title:string;children:React.ReactNode}){return <section className="mt-4 rounded-[22px] border border-green-200/[0.13] bg-[#04170f]/70 p-4 backdrop-blur-2xl sm:p-5"><Stage number={number} label={label}/><h2 className="mt-1.5 text-[clamp(1.4rem,3vw,2rem)] font-semibold text-white">{title}</h2><div className="mt-3">{children}</div></section>}
function Readout({term,value}:{term:string;value:string}){return <div className="rounded-[16px] border border-white/10 bg-white/[0.035] p-4"><dt className="text-[11px] font-semibold uppercase tracking-[.12em] text-stone-500">{term}</dt><dd className="mt-2 text-[14px] leading-6 text-stone-200">{value}</dd></div>}
function MoleculeSketch({kind}:{kind:SampleId}){return <div className="rounded-[17px] border border-white/10 bg-black/20 p-4 text-center"><ChainDiagram kind={kind}/><strong className="mt-2 block text-[14px] text-white">{SAMPLES[kind].name}</strong><span className="text-[12px] text-stone-500">{SAMPLES[kind].form}</span></div>}
function ChainDiagram({kind}:{kind:SampleId}){const count=kind==="glucose"?1:kind==="starch"?7:6;return <div className={`mx-auto flex w-fit items-center gap-1 ${kind==="starch"?"flex-wrap max-w-40 rotate-[-3deg]":""}`}>{Array.from({length:count},(_,i)=><span key={i} className={`grid h-9 w-9 place-items-center border text-[11px] font-bold ${kind==="cellulose"?"rotate-45 border-cyan-200/40 bg-cyan-300/10 text-cyan-100":"rounded-full border-green-200/35 bg-green-300/10 text-green-100"}`}>{kind==="cellulose"?<span className="-rotate-45">G</span>:"G"}</span>)}</div>}
function CarbohydrateField(){return <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_12%_22%,rgba(34,197,94,.24),transparent_28%),radial-gradient(circle_at_85%_58%,rgba(34,211,238,.16),transparent_30%),repeating-linear-gradient(35deg,transparent_0_84px,rgba(134,239,172,.035)_85px_86px),#03140d]" aria-hidden="true"/>}
