"use client";
import dynamic from "next/dynamic";
import { useState } from "react";
import { Anchor, Globe2, Sparkles } from "lucide-react";
import Assessment,{type AssessmentQuestion} from "@/app/_components/Assessment";
import ClassroomLessonShell,{type ClassroomLessonNavItem} from "./ClassroomLessonShell";
import type { ExchangeRouteId } from "./ExchangeRouteMap";
const ExchangeRouteMap=dynamic(()=>import("./ExchangeRouteMap"),{ssr:false,loading:()=><div className="grid h-[330px] place-items-center rounded-[20px] border border-blue-200/15 bg-[#071b2e] text-[14px] text-blue-100/60">Preparing the geographic route map…</div>});
type Props={breadcrumbs:readonly {label:string;href?:string}[];unitHref:string;previous?:ClassroomLessonNavItem;next?:ClassroomLessonNavItem};
type CaseId="tokugawa"|"qing"|"atlantic";
const CASES={tokugawa:{name:"Tokugawa Japan",gate:"Nagasaki and licensed intermediaries",rule:"selected foreign trade and contact were supervised",flow:"silver, copper, silk, books, instruments, and information",limit:"restriction did not eliminate exchange; permission was selective"},qing:{name:"Qing China",gate:"Guangzhou under the Canton system",rule:"approved merchants mediated European maritime commerce",flow:"tea, silk, porcelain, silver, and commercial information",limit:"the system describes a regulated channel, not every Qing relationship"},atlantic:{name:"Atlantic empires",gate:"fortified ports and chartered-company routes",rule:"imperial states and companies claimed and defended access",flow:"goods, people, capital, crops, disease, and knowledge",limit:"large flows included slavery and coercion; reach did not mean equality"}} as const;
const QUIZ:AssessmentQuestion[]=[
 {id:"exchange-channel",type:"mcq",prompt:"Dutch ships traded at Nagasaki under strict supervision. What is best supported?",options:["Japan maintained a controlled channel for some foreign trade","Japan had no contact with outsiders","All Europeans could settle freely"],correctAnswer:"Japan maintained a controlled channel for some foreign trade",explanation:"The evidence shows contact and restriction together; it supports neither total isolation nor unrestricted access."},
 {id:"exchange-map",type:"mcq",prompt:"What can a dense route map establish most directly?",options:["Where recorded movement connected ports","Whether exchange was fair","Why every traveler moved"],correctAnswer:"Where recorded movement connected ports",explanation:"Geography shows connection. Fairness, motive, and coercion require additional evidence."},
 {id:"exchange-compare",type:"mcq",prompt:"Which comparison uses one fixed lens?",options:["Both states concentrated some maritime trade through designated channels","Qing trade used tea while Japan had a shogun","Atlantic empires were simply more open"],correctAnswer:"Both states concentrated some maritime trade through designated channels",explanation:"The claim compares channel design with channel design and avoids ranking whole societies on an open/closed scale."}
];
export default function OutsidersExchangeLesson({breadcrumbs,unitHref,previous,next}:Props){const [caseId,setCaseId]=useState<CaseId>("tokugawa");const [claim,setClaim]=useState<"isolated"|"regulated"|"open"|null>(null);const c=CASES[caseId];return <ClassroomLessonShell subjectTone="social-studies" breadcrumbs={breadcrumbs} eyebrow="Global II · Unit 1 · Key Idea 10.1b" icon={Globe2} title="Outsiders & Exchange" subtitle="Follow gates, rules, and actual movement before calling a society open or closed." stages={["Trace","Define","Gate","Compare","Judge","Practice","Conclude"]} practiceTargetId="exchange-practice" unitHref={unitHref} previous={previous} next={next} lessonPosition="04 / 04" background={<ExchangeField/>}>
 <Section n="1" label="Trace" title="A route proves contact—not freedom."><div className="grid gap-4"><ExchangeRouteMap routeId={caseId as ExchangeRouteId}/><div className="grid gap-3 text-[14px] leading-6 text-stone-300 sm:grid-cols-2"><p>Ships, caravans, merchants, envoys, migrants, and forced laborers connected regions around 1750. Select a case in the gate instrument below to coordinate the map with its policy record.</p><p className="rounded-[15px] border border-blue-200/15 bg-blue-300/[.05] p-3"><strong className="text-blue-100">Map boundary:</strong> a line shows a geographic connection. It cannot by itself show permission, equality, motive, volume, or control.</p></div></div></Section>
 <Section n="2" label="Define" title="Replace the open/closed switch with a gate model."><div className="grid gap-2 sm:grid-cols-4">{[["Rule","Who may enter?"],["Channel","Through which port or intermediary?"],["Enforcement","How is access supervised?"],["Flow","What actually moves?"]].map(([a,b],i)=><div key={a} className="rounded-[16px] border border-white/10 bg-black/20 p-4"><span className="font-mono text-[12px] text-blue-200">0{i+1}</span><strong className="mt-2 block text-white">{a}</strong><span className="mt-1 block text-[13px] text-stone-400">{b}</span></div>)}</div><p className="mt-3 font-mono text-[14px] text-blue-50">policy rule + enforcement + permitted channel → pattern of exchange</p></Section>
 <section className="mt-4 rounded-[22px] border border-blue-200/15 bg-[#061524]/75 p-4 backdrop-blur-2xl sm:p-5"><Stage n="3" label="Gate"/><h2 className="mt-1 text-2xl font-serif font-semibold text-white">Inspect the exchange gate.</h2><div className="mt-4 flex flex-wrap gap-2">{(Object.keys(CASES) as CaseId[]).map(id=><button key={id} onClick={()=>{setCaseId(id);setClaim(null)}} aria-pressed={id===caseId} className={`min-h-11 rounded-full border px-4 text-[14px] ${id===caseId?"border-blue-200/40 bg-blue-300/15 text-white":"border-white/10 text-stone-400"}`}>{CASES[id].name}</button>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-[.8fr_1.2fr]"><div className="grid min-h-64 place-items-center rounded-[20px] border border-blue-200/12 bg-black/20 p-5"><GateDiagram name={c.name}/></div><dl className="grid gap-2"><Readout term="Designated gate" value={c.gate}/><Readout term="Rule and supervision" value={c.rule}/><Readout term="Observed flow" value={c.flow}/><Readout term="Claim limit" value={c.limit}/></dl></div></section>
 <Section n="4" label="Compare" title="Hold the lens still."><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-[14px]"><thead><tr className="text-blue-100"><th className="p-3">Case</th><th className="p-3">Concentrated channel</th><th className="p-3">Historical boundary</th></tr></thead><tbody>{(Object.keys(CASES) as CaseId[]).map(id=><tr key={id} className="border-t border-white/10"><th className="p-3 text-white">{CASES[id].name}</th><td className="p-3 text-stone-300">{CASES[id].gate}</td><td className="p-3 text-stone-400">{CASES[id].limit}</td></tr>)}</tbody></table></div></Section>
 <Section n="5" label="Judge" title="How far can the Nagasaki evidence carry the claim?"><p className="text-[15px] text-stone-300">A record lists Dutch ships entering Nagasaki under strict supervision.</p><div className="mt-3 grid gap-2 sm:grid-cols-3">{(["isolated","regulated","open"] as const).map(x=><button key={x} onClick={()=>setClaim(x)} className={`rounded-[15px] border p-4 text-left ${claim===x?"border-blue-200/40 bg-blue-300/10":"border-white/10"}`}><strong className="capitalize text-white">{x}</strong><span className="mt-1 block text-[12px] text-stone-500">{x==="isolated"?"No exchange existed":x==="regulated"?"Some exchange passed through a controlled channel":"Foreign access was unrestricted"}</span></button>)}</div>{claim&&<p role="status" className={`mt-3 rounded-[14px] border p-3 text-[14px] ${claim==="regulated"?"border-emerald-200/25 bg-emerald-300/10 text-emerald-50":"border-amber-200/25 bg-amber-300/10 text-amber-50"}`}>{claim==="regulated"?"Supported: the record shows both contact and supervision.":"Overextended: the evidence contradicts this all-or-nothing claim."}</p>}</Section>
 <section id="exchange-practice" className="mt-4"><Assessment title="Practice source-bounded comparison" questions={QUIZ}/></section>
 <Section n="7" label="Conclude" title="Exchange passes through institutions."><div className="flex gap-3"><Sparkles size={18} className="mt-1 text-blue-200"/><p className="text-[15px] leading-7 text-stone-300">To compare responses to outsiders, identify the gate, who controlled it, what moved through it, and who bore the costs. “Open” and “closed” erase the mechanism.</p></div></Section>
 </ClassroomLessonShell>}
function Stage({n,label}:{n:string;label:string}){return <p className="font-mono text-[11px] font-semibold uppercase tracking-[.14em] text-blue-200/70">{n.padStart(2,"0")} · {label}</p>};function Section({n,label,title,children}:{n:string;label:string;title:string;children:React.ReactNode}){return <section className="mt-4 rounded-[22px] border border-blue-200/[.13] bg-[#061524]/72 p-4 backdrop-blur-2xl sm:p-5"><Stage n={n} label={label}/><h2 className="mt-1.5 font-serif text-[clamp(1.45rem,3vw,2.05rem)] font-semibold text-white">{title}</h2><div className="mt-3">{children}</div></section>};function Readout({term,value}:{term:string;value:string}){return <div className="rounded-[15px] border border-white/10 bg-white/[.035] p-3"><dt className="text-[11px] uppercase tracking-[.12em] text-stone-500">{term}</dt><dd className="mt-1.5 text-[14px] leading-5 text-stone-200">{value}</dd></div>};function GateDiagram({name}:{name:string}){return <div className="w-full text-center"><Anchor className="mx-auto text-blue-200" size={34}/><div className="mt-3 flex items-center justify-center gap-2"><span className="rounded-full border border-cyan-200/30 px-3 py-2 text-[12px] text-cyan-100">outside movement</span><span className="h-px w-8 bg-blue-200/40"/><span className="rounded-[8px] border-2 border-blue-200/50 bg-blue-300/10 px-3 py-5 text-[12px] text-white">GATE</span><span className="h-px w-8 bg-blue-200/40"/><span className="rounded-full border border-violet-200/30 px-3 py-2 text-[12px] text-violet-100">selected flow</span></div><strong className="mt-4 block font-serif text-white">{name}</strong></div>};function ExchangeField(){return <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(59,130,246,.24),transparent_28%),repeating-linear-gradient(8deg,transparent_0_89px,rgba(125,211,252,.035)_90px_91px),#05101c]" aria-hidden="true"/>}
