import type { VocabTerm } from "../types";

export const inequalitiesVocab: VocabTerm[] = [
  {
    id: "ineq-inequality",
    word: "Inequality",
    definition: "A mathematical statement comparing quantities with symbols such as <, ≤, >, or ≥ instead of saying they are exactly equal.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Core Concept"],
    isAdult: false,
  },
  {
    id: "ineq-solution-set",
    word: "Solution Set",
    definition: "Every value that makes a statement true. An inequality usually has many solutions rather than one exact answer.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Solutions"],
    isAdult: false,
  },
  {
    id: "ineq-boundary",
    word: "Boundary",
    definition: "The value where equality would hold. It separates values that satisfy an inequality from values that do not.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Number Line"],
    isAdult: false,
  },
  {
    id: "ineq-strict",
    word: "Strict Inequality",
    definition: "An inequality using < or >. The boundary is not included in the solution set and is shown with an open endpoint.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Notation"],
    isAdult: false,
  },
  {
    id: "ineq-inclusive",
    word: "Inclusive Inequality",
    definition: "An inequality using ≤ or ≥. The boundary is included in the solution set and is shown with a closed endpoint.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Notation"],
    isAdult: false,
  },
  {
    id: "ineq-interval-notation",
    word: "Interval Notation",
    definition: "A compact way to describe a continuous set of numbers. Parentheses exclude an endpoint; brackets include an endpoint.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Notation"],
    isAdult: false,
  },
  {
    id: "ineq-compound",
    word: "Compound Inequality",
    definition: "Two inequality conditions joined by AND or OR. AND keeps their overlap; OR keeps values satisfying either condition.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Sets"],
    isAdult: false,
  },
  {
    id: "ineq-intersection",
    word: "Intersection",
    definition: "The values shared by two solution sets. In compound inequalities, AND corresponds to intersection.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Sets"],
    isAdult: false,
  },
  {
    id: "ineq-union",
    word: "Union",
    definition: "All values belonging to either of two solution sets. In compound inequalities, OR corresponds to union.",
    domain: "Elementary Algebra",
    tags: ["Inequalities", "Sets"],
    isAdult: false,
  },
];
