import type { VocabTerm } from "../types";

export const informationScienceVocab: VocabTerm[] = [
  {
    id: "info-information",
    word: "Information",
    definition: "Data interpreted within a context so that distinctions can answer a question or support action.",
    domain: "Information Science",
    tags: ["Meaning", "Context"],
    relatedTerms: ["info-data", "info-record"],
    isAdult: false,
  },
  {
    id: "info-data",
    word: "Data",
    definition: "Recorded symbols, measurements, observations, or assertions that can be stored, processed, and interpreted.",
    domain: "Information Science",
    tags: ["Representation", "Observation"],
    relatedTerms: ["info-information"],
    isAdult: false,
  },
  {
    id: "info-record",
    word: "Record",
    definition: "An information object kept as evidence of an activity, event, transaction, observation, or decision.",
    domain: "Information Science",
    tags: ["Evidence", "Stewardship"],
    relatedTerms: ["info-document", "info-provenance"],
    isAdult: false,
  },
  {
    id: "info-document",
    word: "Document",
    definition: "A bounded information object whose content and form can be identified, communicated, interpreted, or preserved.",
    domain: "Information Science",
    tags: ["Object", "Communication"],
    relatedTerms: ["info-record"],
    isAdult: false,
  },
  {
    id: "info-collection",
    word: "Collection",
    definition: "A deliberately assembled group of information objects whose selection, description, arrangement, and access shape what can be found.",
    domain: "Information Science",
    tags: ["Repository", "Selection"],
    relatedTerms: ["info-record", "info-coverage"],
    isAdult: false,
  },
  {
    id: "info-context",
    word: "Context",
    definition: "The surrounding purpose, relationships, conventions, provenance, time, place, and audience needed to interpret information.",
    domain: "Information Science",
    tags: ["Meaning", "Use"],
    relatedTerms: ["info-information", "info-provenance"],
    isAdult: false,
  },
  {
    id: "info-information-system",
    word: "Information System",
    definition: "A coordinated arrangement of people, practices, representations, technologies, and institutions that manages information across a lifecycle.",
    domain: "Information Science",
    tags: ["System", "Lifecycle"],
    relatedTerms: ["info-information-lifecycle"],
    isAdult: false,
  },
  {
    id: "info-information-lifecycle",
    word: "Information Lifecycle",
    definition: "The changing sequence through which information is created or observed, represented, described, organized, accessed, used, preserved, and disposed.",
    domain: "Information Science",
    tags: ["Process", "Stewardship"],
    relatedTerms: ["info-information-system"],
    isAdult: false,
  },
  {
    id: "info-identity",
    word: "Identity",
    definition: "The rule or evidence used to decide which records, names, identifiers, or representations refer to the same entity.",
    domain: "Information Science",
    tags: ["Reference", "Entities"],
    relatedTerms: ["info-identifier", "info-entity-resolution"],
    isAdult: false,
  },
  {
    id: "info-identifier",
    word: "Identifier",
    definition: "A name, number, or token assigned within a scheme to distinguish and refer to an entity or information object.",
    domain: "Information Science",
    tags: ["Identity", "Reference"],
    relatedTerms: ["info-identity"],
    isAdult: false,
  },
  {
    id: "info-coverage",
    word: "Coverage",
    definition: "The people, places, periods, languages, formats, subjects, or object types included and excluded by a collection or system.",
    domain: "Information Science",
    tags: ["Boundary", "Collections"],
    relatedTerms: ["info-collection", "info-selection-bias"],
    isAdult: false,
  },
  {
    id: "info-provenance",
    word: "Provenance",
    definition: "Documented information about an object's origin, custody, transformations, sources, and responsibility over time.",
    domain: "Information Science",
    tags: ["Evidence", "Context"],
    relatedTerms: ["info-record", "info-metadata"],
    isAdult: false,
  },
];
