export const VISUAL_ARTS_BRANCH_IDS = [
  "humanities.visual-arts.painting",
  "humanities.visual-arts.sculpture",
  "humanities.visual-arts.photography",
  "humanities.visual-arts.printmaking",
  "humanities.visual-arts.digital-media",
  "humanities.visual-arts.art-history",
] as const;

export type VisualArtsBranchId = (typeof VISUAL_ARTS_BRANCH_IDS)[number];
export type HueRelationship =
  | "complementary"
  | "analogous"
  | "triadic"
  | "split";

export function normalizeHue(value: number): number {
  return ((Math.round(value) % 360) + 360) % 360;
}

export function getHarmonyHues(
  hue: number,
  relationship: HueRelationship
): number[] {
  const offsets: Record<HueRelationship, readonly number[]> = {
    complementary: [0, 180],
    analogous: [-30, 0, 30],
    triadic: [0, 120, 240],
    split: [0, 150, 210],
  };

  return offsets[relationship].map((offset) => normalizeHue(hue + offset));
}

export const VISUAL_ARTS_EVIDENCE_CASES = [
  {
    id: "hue-calculation",
    label: "Calculate hue distance",
    eyebrow: "Practice 01 · exact relationship",
    observation:
      "The teaching wheel places a complementary hue 180° from the base hue and wraps every result into the interval from 0° through 359°.",
    prompt: "What complement does the wheel assign to a base hue of 18°?",
    options: [
      { id: "198", label: "198°, because (18 + 180) mod 360 = 198." },
      { id: "162", label: "162°, because 180 − 18 = 162." },
      { id: "342", label: "342°, because 360 − 18 = 342." },
    ],
    correctOptionId: "198",
    success:
      "Correct. The wheel adds a 180° separation to the starting angle. This is a geometric hue relationship, not a promise of equal perceptual contrast.",
    correction:
      "Begin at 18°, add the complementary offset of 180°, and wrap only if the result reaches 360°. The answer is 198°.",
  },
  {
    id: "observation-interpretation",
    label: "Separate seeing from claiming",
    eyebrow: "Practice 02 · visual analysis",
    observation:
      "A painted surface contains repeated diagonal cobalt marks, one small amber circle, and a large area of dark ground. No statement from the maker is available.",
    prompt:
      "Which sentence is the strongest first claim supported by the object alone?",
    options: [
      {
        id: "formal-observation",
        label:
          "Repeated blue diagonals establish a directional rhythm, while the isolated amber circle becomes a contrasting focal point.",
      },
      {
        id: "maker-intention",
        label:
          "The maker intended the amber circle to represent hope overcoming despair.",
      },
      {
        id: "universal-response",
        label:
          "Every viewer will experience the dark ground as sadness and the circle as relief.",
      },
    ],
    correctOptionId: "formal-observation",
    success:
      "Exactly. The first claim names visible relationships. Intention, symbolism, and viewer response may be investigated, but they require additional contextual evidence.",
    correction:
      "Start with features another viewer could inspect in the object. Claims about intention or universal emotion need evidence beyond the visible arrangement.",
  },
  {
    id: "process-evidence",
    label: "Infer from process",
    eyebrow: "Practice 03 · medium and making",
    observation:
      "Six paper impressions share the same carved contour. Ink density and registration vary slightly from sheet to sheet, and the group is numbered 1/6 through 6/6.",
    prompt:
      "Which inference best joins the material evidence to a making process?",
    options: [
      {
        id: "matrix-edition",
        label:
          "A reusable matrix generated an edition; repeated structure can coexist with variation between impressions.",
      },
      {
        id: "six-paintings",
        label:
          "Each sheet must be an unrelated painting because no two ink surfaces are perfectly identical.",
      },
      {
        id: "digital-proof",
        label:
          "Numbering alone proves the images were generated by a digital printer.",
      },
    ],
    correctOptionId: "matrix-edition",
    success:
      "Right. Shared contours and edition numbering support a repeatable matrix process, while small differences preserve evidence of individual impressions.",
    correction:
      "Use all of the evidence together: repeated contours, variable ink, registration, and edition numbering. No single clue establishes an unrelated or specifically digital process.",
  },
  {
    id: "record-boundary",
    label: "Read a museum record",
    eyebrow: "Practice 04 · provenance and rights",
    observation:
      "A provider record names a title, maker, date, medium, department, credit line, object URL, and ‘public domain: yes.’ It does not list a complete ownership history.",
    prompt:
      "What can the displayed record support without inventing missing evidence?",
    options: [
      {
        id: "bounded-record",
        label:
          "It supports cited object metadata and a public-domain image status, but not a complete chain of ownership or an uncontested interpretation.",
      },
      {
        id: "complete-provenance",
        label:
          "The credit line proves every transfer of ownership from the work’s creation to the present.",
      },
      {
        id: "rights-equals-truth",
        label:
          "Public-domain image status proves that every description and historical interpretation of the object is correct.",
      },
    ],
    correctOptionId: "bounded-record",
    success:
      "Correct. A responsible collection interface shows what the provider supplied, names the source, distinguishes image rights from object history, and leaves absent evidence absent.",
    correction:
      "Separate fields with different jobs. Image rights, tombstone metadata, provenance, and interpretation are related, but none automatically supplies the others.",
  },
] as const;

export type VisualArtsEvidenceCaseId =
  (typeof VISUAL_ARTS_EVIDENCE_CASES)[number]["id"];

export function isVisualArtsEvidenceAnswerCorrect(
  caseId: string,
  optionId: string
): boolean {
  const evidenceCase = VISUAL_ARTS_EVIDENCE_CASES.find(
    (item) => item.id === caseId
  );
  return evidenceCase?.correctOptionId === optionId;
}
