import DomainPageHeader from "@/app/_components/DomainPageHeader";
import { requireCurriculumPageContext } from "@/lib/curriculum/page-context";
import { Clock3, Layers3, Mountain, Orbit, Pickaxe, Waves } from "lucide-react";
import RockCycleLab from "./RockCycleLab";
import TectonicBackground from "./TectonicBackground";

const NODE_ID = "natural.earth-science.geology";
const BOUNDARIES = [
  { label: "Divergent", motion: "←   →", result: "Extension · rifting · seafloor spreading", detail: "Plates move apart. Mantle material rises, decompression melting can generate magma, and new lithosphere may form along spreading centers.", rgb: "34, 211, 238" },
  { label: "Convergent", motion: "→   ←", result: "Subduction · collision · mountain building", detail: "Plates approach one another. Outcomes depend on lithosphere type and density, producing trenches, volcanic arcs, crustal shortening, or continental collision.", rgb: "248, 113, 113" },
  { label: "Transform", motion: "⇄", result: "Strike-slip motion · earthquakes", detail: "Plates slide laterally past one another. Lithosphere is neither created nor destroyed at the boundary, but strain can accumulate and release suddenly.", rgb: "250, 204, 21" },
] as const;
const TIME_SCALES = [
  ["Seconds → years", "Earthquakes, eruptions, landslides, floods, weathering events, and human-observed deformation."],
  ["Thousands → millions of years", "River incision, sedimentary basin filling, mountain erosion, fault displacement, glaciation, and landscape evolution."],
  ["Tens → hundreds of millions of years", "Ocean basins open and close, supercontinents assemble and break apart, mountain belts rise and erode, and crust is recycled."],
  ["Billions of years", "Continental crust evolves, atmosphere and oceans change, and the geologic record preserves only fragments of Earth's earliest history."],
] as const;
const RECORDS = [
  { icon: Layers3, label: "Strata", note: "Layer relationships, sedimentary structures, unconformities, and depositional environments." },
  { icon: Pickaxe, label: "Rocks & minerals", note: "Texture, composition, mineral assemblages, isotopes, and alteration record formation conditions." },
  { icon: Waves, label: "Landforms", note: "Topography and drainage reveal erosion, deposition, uplift, glaciation, volcanism, and tectonic structure." },
  { icon: Orbit, label: "Geophysics", note: "Seismic waves, gravity, magnetism, heat flow, and deformation probe structures that cannot be observed directly." },
] as const;

export default function GeologyPage() {
  const context = requireCurriculumPageContext(NODE_ID);
  return <main className="relative min-h-screen overflow-x-hidden bg-[#0c0907] text-slate-100 selection:bg-orange-400/25">
    <TectonicBackground /><div className="pointer-events-none fixed inset-0 z-0 bg-[radial-gradient(circle_at_80%_16%,rgba(249,115,22,0.10),transparent_30%),radial-gradient(circle_at_16%_82%,rgba(250,204,21,0.045),transparent_28%),linear-gradient(to_bottom,rgba(12,9,7,0.10),rgba(12,9,7,0.76)_76%,rgba(8,6,5,0.97))]" aria-hidden="true" />
    <div className="relative z-10 mx-auto w-full max-w-[1580px] px-4 pb-14 sm:px-6 xl:px-8">
      <div className="sticky top-0 z-30 -mx-4 border-b border-white/[0.06] bg-[#0c0907]/80 px-4 pb-3 pt-5 backdrop-blur-2xl sm:-mx-6 sm:px-6 xl:-mx-8 xl:px-8"><DomainPageHeader breadcrumbs={context.breadcrumbs} eyebrow="Rock · tectonics · surface process · deep time" eyebrowStyle="rule" icon={Mountain} title={<span>Geology</span>} subtitle="Geology reconstructs a dynamic planet from incomplete evidence. Rocks transform, plates move, landscapes erode, magma rises, sediments accumulate, and the record is buried, deformed, recycled, and exposed again across timescales far longer than direct observation." accentRgb="249, 115, 22" titleClassName="font-sans text-[clamp(3rem,5.7vw,6.3rem)] font-semibold leading-[0.83] tracking-[-0.067em] text-[#fff8f1]" headerClassName="border-orange-100/[0.10]" /></div>
      <section className="mt-5 overflow-hidden rounded-[30px] border border-orange-200/[0.10] bg-black/[0.14] backdrop-blur-xl"><div className="grid gap-4 border-b border-white/[0.07] px-5 py-5 lg:grid-cols-[minmax(0,1fr)_420px] lg:items-end sm:px-6"><div><div className="flex items-center gap-2 font-mono text-[9px] font-semibold uppercase tracking-[0.14em] text-orange-200/58"><Orbit size={12}/> Planetary process</div><h2 className="mt-2 text-[clamp(1.9rem,3.6vw,3.3rem)] font-semibold leading-[0.94] tracking-[-0.05em] text-white">Geology connects material cycles to a moving lithosphere.</h2></div><p className="text-[12px] leading-6 text-slate-400">Plate motion changes pressure, temperature, elevation, basin geometry, magma generation, erosion, burial, and exposure. The rock cycle and plate tectonics are two views of the same evolving Earth.</p></div><div className="grid lg:grid-cols-3">{BOUNDARIES.map((item,index)=><article key={item.label} className="min-h-[230px] border-b border-white/[0.06] px-5 py-5 lg:border-b-0 lg:border-r lg:last:border-r-0"><div className="flex items-center justify-between"><span className="font-mono text-[8px] text-slate-700">0{index+1}</span><span className="font-mono text-[18px]" style={{color:`rgb(${item.rgb})`}}>{item.motion}</span></div><h3 className="mt-5 text-[16px] font-semibold text-white">{item.label}</h3><div className="mt-1 font-mono text-[8px] uppercase" style={{color:`rgba(${item.rgb},0.62)`}}>{item.result}</div><p className="mt-3 text-[10px] leading-5 text-slate-600">{item.detail}</p></article>)}</div></section>
      <div className="mt-6"><RockCycleLab /></div>
      <section className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,0.85fr)]"><div className="overflow-hidden rounded-[28px] border border-white/[0.08] bg-black/[0.13] backdrop-blur-xl"><div className="border-b border-white/[0.07] px-5 py-5 sm:px-6"><div className="flex items-center gap-2 font-mono text-[9px] uppercase text-amber-200/52"><Clock3 size={12}/> Deep-time ruler</div><h2 className="mt-2 text-[clamp(1.7rem,3vw,2.8rem)] font-semibold tracking-[-0.045em] text-white">Different geologic processes become visible at different clocks.</h2></div><div className="grid sm:grid-cols-2">{TIME_SCALES.map(([scale,detail],index)=><article key={scale} className="min-h-[165px] border-b border-white/[0.06] px-5 py-4 sm:border-r sm:[&:nth-child(2n)]:border-r-0"><span className="font-mono text-[8px] text-orange-200/34">0{index+1}</span><h3 className="mt-3 text-[12px] font-semibold text-white/84">{scale}</h3><p className="mt-2 text-[10px] leading-5 text-slate-600">{detail}</p></article>)}</div></div><aside className="rounded-[28px] border border-white/[0.08] bg-black/[0.13] p-5 backdrop-blur-xl sm:p-6"><div className="font-mono text-[9px] uppercase text-stone-400/58">Reading the record</div><h2 className="mt-2 text-[23px] font-semibold tracking-[-0.04em] text-white">Earth rarely preserves a complete story.</h2><p className="mt-3 text-[11px] leading-5 text-slate-500">Geologists combine independent records, infer processes from present-day physics and chemistry, and distinguish observed relationships from reconstructed history.</p><div className="mt-5 space-y-1">{RECORDS.map(item=>{const Icon=item.icon;return <div key={item.label} className="grid grid-cols-[34px_92px_minmax(0,1fr)] items-start gap-3 border-b border-white/[0.055] py-3 last:border-b-0"><span className="flex h-7 w-7 items-center justify-center rounded-full border border-orange-200/[0.12] text-orange-200/48"><Icon size={12}/></span><strong className="pt-1 text-[10px] text-white/78">{item.label}</strong><span className="pt-1 text-[9px] leading-4 text-slate-600">{item.note}</span></div>})}</div></aside></section>
    </div>
  </main>;
}
