import type { VocabTerm } from "../types";

export const graphTheoryVocab: VocabTerm[] = [
  {
    id: "graph-vertex",
    word: "Vertex",
    definition: "An object represented as a point in a graph.",
    domain: "Graph Theory",
    tags: ["Graphs", "Objects"],
    relatedTerms: ["graph-edge", "graph-degree"],
    isAdult: false,
  },
  {
    id: "graph-edge",
    word: "Edge",
    definition: "A connection joining a pair of vertices in a graph.",
    domain: "Graph Theory",
    tags: ["Graphs", "Relations"],
    relatedTerms: ["graph-vertex", "graph-adjacent", "graph-path"],
    isAdult: false,
  },
  {
    id: "graph-adjacent",
    word: "Adjacent Vertices",
    definition: "Two vertices that are joined directly by an edge in a graph.",
    domain: "Graph Theory",
    tags: ["Graphs", "Relations"],
    relatedTerms: ["graph-vertex", "graph-edge", "graph-degree"],
    isAdult: false,
  },
  {
    id: "graph-degree",
    word: "Degree",
    definition: "The number of edges incident to a vertex.",
    domain: "Graph Theory",
    tags: ["Graphs", "Measurement"],
    relatedTerms: ["graph-vertex", "graph-edge"],
    isAdult: false,
  },
  {
    id: "graph-walk",
    word: "Walk",
    definition:
      "A sequence of vertices in which each consecutive pair is joined by an edge; vertices and edges may repeat.",
    domain: "Graph Theory",
    tags: ["Graphs", "Routes"],
    relatedTerms: ["graph-trail", "graph-path"],
    isAdult: false,
  },
  {
    id: "graph-trail",
    word: "Trail",
    definition: "A walk that does not repeat an edge.",
    domain: "Graph Theory",
    tags: ["Graphs", "Routes"],
    relatedTerms: ["graph-walk", "graph-path"],
    isAdult: false,
  },
  {
    id: "graph-path",
    word: "Path",
    definition:
      "A sequence of distinct vertices in which each consecutive pair is joined by an edge.",
    domain: "Graph Theory",
    tags: ["Graphs", "Traversal"],
    relatedTerms: [
      "graph-walk",
      "graph-trail",
      "graph-edge",
      "graph-connected",
    ],
    isAdult: false,
  },
  {
    id: "graph-connected",
    word: "Connected Graph",
    definition:
      "A graph in which a path exists between every pair of vertices.",
    domain: "Graph Theory",
    tags: ["Graphs", "Connectivity"],
    relatedTerms: ["graph-path", "graph-component", "graph-tree"],
    isAdult: false,
  },
  {
    id: "graph-component",
    word: "Connected Component",
    definition:
      "A maximal connected part of a graph: its vertices reach one another, and no additional graph vertex can be included while preserving that property.",
    domain: "Graph Theory",
    tags: ["Graphs", "Connectivity"],
    relatedTerms: ["graph-connected", "graph-path"],
    isAdult: false,
  },
  {
    id: "graph-cycle",
    word: "Cycle",
    definition:
      "A closed route that returns to its starting vertex without repeating another vertex along the way.",
    domain: "Graph Theory",
    tags: ["Graphs", "Routes"],
    relatedTerms: ["graph-path", "graph-tree"],
    isAdult: false,
  },
  {
    id: "graph-tree",
    word: "Tree",
    definition: "A connected graph that contains no cycle.",
    domain: "Graph Theory",
    tags: ["Graphs", "Structure"],
    relatedTerms: ["graph-connected", "graph-cycle"],
    isAdult: false,
  },
  {
    id: "graph-bfs",
    word: "Breadth-First Search",
    definition:
      "A traversal method that explores vertices in layers of increasing edge distance from a chosen start vertex.",
    domain: "Graph Theory",
    tags: ["Graphs", "Traversal", "Algorithms"],
    relatedTerms: ["graph-path", "graph-connected"],
    isAdult: false,
  },
];
