"use client";
import Link from "next/link";
import { M } from "@/components/Math";
import TeslaBackground from "@/app/natural-science/physics/electromagnetism/TeslaBackground";
import { ArrowLeft, Zap, Magnet, Activity, Radio, Sun, BatteryCharging } from "lucide-react";

// --- MAXWELL'S EQUATIONS DATA ---
const maxwellEquations = [
  {
    name: "Gauss's Law",
    symbol: "E",
    eq: "\\nabla \\cdot \\mathbf{E} = \\frac{\\rho}{\\epsilon_0}",
    meaning: "Electric charges produce electric fields. Like charges repel, opposites attract.",
    icon: Zap,
    color: "text-amber-400",
    border: "group-hover:border-amber-400",
    bg: "group-hover:bg-amber-400/10"
  },
  {
    name: "Gauss's Law (Magnetism)",
    symbol: "B",
    eq: "\\nabla \\cdot \\mathbf{B} = 0",
    meaning: "There are no magnetic monopoles. Magnetic field lines always form closed loops.",
    icon: Magnet,
    color: "text-red-400",
    border: "group-hover:border-red-400",
    bg: "group-hover:bg-red-400/10"
  },
  {
    name: "Faraday's Law",
    symbol: "Induction",
    eq: "\\nabla \\times \\mathbf{E} = -\\frac{\\partial \\mathbf{B}}{\\partial t}",
    meaning: "A changing magnetic field creates an electric field. This is how generators work.",
    icon: Activity,
    color: "text-cyan-400",
    border: "group-hover:border-cyan-400",
    bg: "group-hover:bg-cyan-400/10"
  },
  {
    name: "Ampère-Maxwell Law",
    symbol: "Unified",
    eq: "\\nabla \\times \\mathbf{B} = \\mu_0\\mathbf{J} + \\mu_0\\epsilon_0\\frac{\\partial \\mathbf{E}}{\\partial t}",
    meaning: "Magnetic fields are generated by electric currents and changing electric fields.",
    icon: Radio,
    color: "text-violet-400",
    border: "group-hover:border-violet-400",
    bg: "group-hover:bg-violet-400/10"
  }
];

export default function ElectromagnetismPage() {
  return (
    <main className="relative min-h-screen bg-[#050508] text-white overflow-hidden selection:bg-cyan-500/30 font-sans">
      
      {/* 1. VISUAL ENGINE */}
      <TeslaBackground />
      
      {/* 2. NAVIGATION OVERLAY */}
      <div className="absolute top-6 left-6 z-20">
         <Link href="/natural-science/physics" className="flex items-center gap-2 text-xs font-mono text-cyan-500/60 hover:text-cyan-400 transition-colors uppercase tracking-widest">
            <ArrowLeft size={14} /> Return to Collider
         </Link>
      </div>

      <div className="relative z-10 container mx-auto px-6 py-20 max-w-6xl">
        
        {/* HEADER: The Capacitor */}
        <div className="flex flex-col md:flex-row items-end justify-between border-b border-cyan-900/30 pb-8 mb-12">
            <div>
                <h1 className="text-6xl md:text-8xl font-black tracking-tighter text-white mb-2 drop-shadow-[0_0_15px_rgba(6,182,212,0.5)]">
                    ELECTRO<br/>MAGNETISM
                </h1>
                <p className="text-cyan-200/60 font-mono max-w-xl text-sm md:text-base">
                    The interaction of electric currents and magnetic fields. The force that binds atoms and lights the universe.
                </p>
            </div>
            
            {/* Status Indicator */}
            <div className="hidden md:flex flex-col items-end gap-2 text-cyan-500/40 font-mono text-xs">
                <div className="flex items-center gap-2">
                    <div className="w-2 h-2 bg-cyan-500 animate-pulse rounded-full" />
                    <span>FIELD: ACTIVE</span>
                </div>
                <div>c = 299,792,458 m/s</div>
            </div>
        </div>

        {/* SECTION 1: THE SOURCE CODE (Maxwell's Equations) */}
        <div className="mb-20">
            <div className="flex items-center gap-2 mb-6 opacity-80">
                <Sun size={16} className="text-cyan-400" />
                <h3 className="text-xs font-bold tracking-[0.2em] text-cyan-400">THE SOURCE CODE</h3>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {maxwellEquations.map((item) => (
                    <div 
                        key={item.name}
                        className={`
                            group relative p-8 rounded-xl border border-white/10 bg-neutral-900/40 backdrop-blur-md
                            transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_0_30px_-10px_rgba(6,182,212,0.3)]
                            ${item.border}
                        `}
                    >
                        {/* Glow Effect */}
                        <div className={`absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-500 rounded-xl ${item.bg}`} />

                        <div className="relative z-10 flex flex-col h-full justify-between gap-6">
                            <div className="flex justify-between items-start">
                                <div className="flex items-center gap-3">
                                    <div className={`p-2 rounded bg-white/5 ${item.color}`}>
                                        <item.icon size={20} />
                                    </div>
                                    <h4 className="font-bold text-white tracking-wide">{item.name}</h4>
                                </div>
                                <span className={`text-4xl font-serif opacity-20 group-hover:opacity-100 transition-opacity ${item.color}`}>
                                    {item.symbol}
                                </span>
                            </div>

                            {/* The Equation */}
                            <div className="text-2xl md:text-3xl font-serif text-center py-4">
                                <M>{item.eq}</M>
                            </div>

                            {/* The Meaning (Revealed on hover-ish/always visible but dim) */}
                            <p className="text-sm text-neutral-400 group-hover:text-white transition-colors border-t border-white/5 pt-4">
                                {item.meaning}
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </div>


        {/* SECTION 2: THE PHENOMENA (Lorentz Force & Light) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            
            {/* LEFT: Lorentz Force Card */}
            <div className="lg:col-span-8 p-8 rounded-2xl bg-gradient-to-br from-indigo-950/50 to-neutral-900/50 border border-indigo-500/20 relative overflow-hidden">
                <div className="relative z-10">
                    <h3 className="text-2xl font-bold text-indigo-300 mb-2">The Lorentz Force</h3>
                    <div className="text-4xl font-serif text-white mb-6">
                        <M>{"\\mathbf{F} = q(\\mathbf{E} + \\mathbf{v} \\times \\mathbf{B})"}</M>
                    </div>
                    <p className="text-indigo-200/60 max-w-2xl leading-relaxed">
                        This is the bridge between the fields and matter. It describes how a charged particle moves through electromagnetic space. 
                        The <span className="text-white">Electric Field (E)</span> pushes it, while the <span className="text-white">Magnetic Field (B)</span> twists its path.
                    </p>
                </div>
                {/* Decorative graphic */}
                <div className="absolute top-0 right-0 w-64 h-full bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-indigo-500/10 to-transparent pointer-events-none" />
            </div>

            {/* RIGHT: Light/Circuit */}
            <div className="lg:col-span-4 p-8 rounded-2xl bg-neutral-900/40 border border-white/10 flex flex-col justify-center items-center text-center relative overflow-hidden group">
                 <div className="absolute inset-0 bg-cyan-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
                 
                 <BatteryCharging size={48} className="text-cyan-400 mb-4" />
                 <h3 className="text-xl font-bold text-white mb-2">Electrodynamics</h3>
                 <p className="text-sm text-neutral-400 mb-4">
                    From the battery in your phone to the lightning in the sky.
                 </p>
                 <div className="w-full bg-neutral-800 h-1 rounded-full overflow-hidden">
                     <div className="h-full bg-cyan-400 w-1/2 animate-[shimmer_2s_infinite_linear] relative overflow-hidden">
                        <div className="absolute inset-0 bg-white/50 -skew-x-12 translate-x-[-100%] animate-[scanline_1s_infinite]" />
                     </div>
                 </div>
                 <span className="text-[10px] font-mono text-cyan-500 mt-2">CHARGING...</span>
            </div>

        </div>

      </div>
    </main>
  );
}