"use client";

import { useState } from "react";
import Link from "next/link";
import DiscreteBackground from "./_components/DiscreteBackground"; 
import ModularClockWidget from "./_components/ModularClockWidget";
import LagrangeWidget from "./_components/LagrangeWidget";
import { M } from "@/app/_components/Math";
import { 
  Circle, Shuffle, Crown, Hash, Layers, 
  Binary, LayoutGrid, ArrowRight,
  Globe, Key, ArrowLeft
} from "lucide-react";

export default function FiniteGroupsPage() {
  return (
    <main className="relative min-h-screen w-full overflow-hidden bg-[#090211] text-white selection:bg-purple-500/30 font-sans pb-32">
      
      {/* 1. Background */}
      <DiscreteBackground /> 
      
      {/* 2. UI CONTAINER */}
      <div className="relative z-10 max-w-6xl mx-auto px-6 py-12 flex flex-col gap-24">
        
        {/* HEADER */}
        <header>
             <Link href="/formal-science/mathematics/algebra/abstract-algebra/group-theory" className="flex items-center gap-2 text-xs text-purple-400 hover:text-white transition-colors mb-8 uppercase tracking-widest group bg-black/40 px-4 py-2 rounded-full border border-purple-500/30 backdrop-blur-md w-max shadow-lg">
                <ArrowLeft size={12} className="group-hover:-translate-x-1 transition-transform"/> Group_Theory // Sub_01
             </Link>
             <div className="flex flex-col md:flex-row items-start md:items-end gap-6 border-b border-cyan-500/30 pb-8">
                 <div className="p-4 bg-cyan-500/10 border border-cyan-500/30 rounded-2xl backdrop-blur-md shadow-[0_0_30px_rgba(6,182,212,0.2)] group relative overflow-hidden">
                    <Binary size={48} className="text-cyan-400 relative z-10 group-hover:scale-110 transition-transform" />
                 </div>
                 <div>
                    <h1 className="text-5xl md:text-7xl font-black text-white tracking-tighter mb-4 drop-shadow-lg uppercase">
                       FINITE GROUPS
                    </h1>
                    <p className="text-cyan-100/60 max-w-2xl text-lg leading-relaxed font-light border-l-2 border-cyan-500/50 pl-6">
                        The study of symmetries with limits. Unlike continuous groups, finite groups have a strictly countable number of elements. They are the discrete pixels of mathematical structure.
                    </p>
                 </div>
             </div>
        </header>

        {/* SECTION 1: INTRODUCTION & CAYLEY */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div>
                <div className="flex items-center gap-3 mb-6">
                    <div className="h-px w-8 bg-cyan-500" />
                    <h2 className="text-xl font-bold text-cyan-300 uppercase tracking-widest">01 // Discrete Sets</h2>
                </div>
                <p className="text-zinc-300 leading-relaxed mb-8">
                    In a finite group, you can theoretically list out every single element and map every possible interaction. Because the set is closed, repeating any operation will eventually loop back to the identity element.
                </p>

                <div className="flex flex-col gap-4">
                    <DefinitionCard 
                        term={<>Order <M>|G|</M></>} 
                        def="The absolute number of elements in a group. If it is countable, the group is finite."
                        icon={Hash}
                        color="text-purple-400"
                    />
                    <DefinitionCard 
                        term="Simple Group" 
                        def="A group with no non-trivial normal subgroups. The unbreakable 'prime numbers' of algebra."
                        icon={Crown}
                        color="text-fuchsia-400"
                    />
                </div>
            </div>

            <div className="relative border border-cyan-500/30 rounded-3xl bg-black/60 backdrop-blur-xl p-4 shadow-2xl flex justify-center">
                [Image of a Cayley graph of a finite group showing discrete symmetrical structure]
            </div>
        </section>

        {/* SECTION 2: CYCLIC GROUPS & LAB */}
        <section className="space-y-12">
            <div>
                <div className="flex items-center gap-3 mb-6">
                    <div className="h-px w-8 bg-cyan-500" />
                    <h2 className="text-xl font-bold text-cyan-300 uppercase tracking-widest">02 // Cyclic Generators</h2>
                </div>
                <h3 className="text-3xl font-black text-white mb-4 flex items-center gap-3">
                    <Circle className="text-cyan-400" /> Modular Arithmetic
                </h3>
                <p className="text-zinc-400 leading-relaxed max-w-3xl">
                    Cyclic groups are the simplest finite groups in existence. They are generated by a single element repeating its operation until it loops back. Think of a standard clock face: <M>{"12 + 1 \\equiv 1 \\pmod{12}"}</M>.
                </p>
            </div>

            <ModularClockWidget />
            [Image of clock arithmetic showing modular addition for a cyclic group]

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-black/40 p-8 rounded-3xl border border-white/10 shadow-inner">
                    <h4 className="text-lg font-bold text-white mb-3 flex items-center gap-3"><Key className="text-purple-400"/> Cryptography</h4>
                    <p className="text-sm text-zinc-400 leading-relaxed">RSA encryption relies heavily on the discrete logarithm problem within massive cyclic groups formed by prime numbers.</p>
                </div>
                <div className="bg-black/40 p-8 rounded-3xl border border-white/10 shadow-inner">
                    <h4 className="text-lg font-bold text-white mb-3 flex items-center gap-3"><Globe className="text-cyan-400"/> Signal Processing</h4>
                    <p className="text-sm text-zinc-400 leading-relaxed">Roots of unity (which form cyclic groups) act as the strict mathematical foundation for the Discrete Fourier Transform.</p>
                </div>
            </div>
        </section>

        {/* SECTION 3: SYMMETRIC GROUPS */}
        <section className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
            <div className="lg:col-span-5 space-y-6">
                <div className="flex items-center gap-3">
                    <div className="h-px w-8 bg-fuchsia-500" />
                    <h2 className="text-xl font-bold text-fuchsia-300 uppercase tracking-widest">03 // Permutations</h2>
                </div>
                <h3 className="text-3xl font-black text-white mb-4 flex items-center gap-3">
                    <Shuffle className="text-fuchsia-400" /> The Mother Group
                </h3>
                <p className="text-zinc-400 leading-relaxed mb-6">
                    The Symmetric Group <M>S_n</M> consists of all possible shuffles of <M>n</M> distinct items. Cayley's Theorem physically proves that every finite group lives hidden inside a Symmetric Group.
                </p>

                <div className="p-6 rounded-2xl bg-fuchsia-950/20 border border-fuchsia-500/30 mb-8 shadow-inner">
                    <h4 className="text-xs font-bold uppercase tracking-widest text-fuchsia-400 mb-4 border-b border-fuchsia-500/20 pb-2">Cycle Notation Translation</h4>
                    <div className="flex items-center gap-6">
                        <div className="text-2xl font-mono text-white font-black"><M>{"(1\\ 2\\ 3)"}</M></div>
                        <ArrowRight className="text-fuchsia-500" />
                        <div className="text-sm text-zinc-300 font-mono bg-black/60 p-4 rounded-xl border border-white/5 leading-loose">
                            1 <ArrowRight size={14} className="inline text-fuchsia-400 mx-2"/> 2 <br/>
                            2 <ArrowRight size={14} className="inline text-fuchsia-400 mx-2"/> 3 <br/>
                            3 <ArrowRight size={14} className="inline text-fuchsia-400 mx-2"/> 1
                        </div>
                    </div>
                </div>
            </div>

            <div className="lg:col-span-7 flex justify-center">
                <div className="relative border border-fuchsia-500/30 rounded-3xl bg-black/60 backdrop-blur-xl p-4 shadow-2xl">
                    [Image of cycle notation permutation mapping on a set of elements]
                </div>
            </div>
        </section>

        {/* SECTION 4: STRUCTURE & LAGRANGE LAB */}
        <section className="space-y-12">
            <div>
                <div className="flex items-center gap-3 mb-6">
                    <div className="h-px w-8 bg-purple-500" />
                    <h2 className="text-xl font-bold text-purple-300 uppercase tracking-widest">04 // Rigid Architecture</h2>
                </div>
                <h3 className="text-3xl font-black text-white mb-4 flex items-center gap-3">
                    <Layers className="text-purple-400" /> Lagrange's Theorem
                </h3>
                <p className="text-zinc-400 leading-relaxed max-w-3xl">
                    Groups are not random bags of elements; they have highly rigid internal architecture. Lagrange's Theorem states that the order of any subgroup <M>H</M> must perfectly divide the order of the parent group <M>G</M>. This forces mathematical symmetry to be strictly quantized.
                </p>
            </div>

            <LagrangeWidget />
        </section>

        {/* SECTION 5: CLASSIFICATION & THE MONSTER */}
        <section>
            <div className="flex items-center gap-3 mb-8">
                <div className="h-px w-8 bg-emerald-500" />
                <h2 className="text-xl font-bold text-emerald-300 uppercase tracking-widest">05 // The Periodic Table</h2>
            </div>
            
            <p className="text-zinc-400 mb-8 leading-relaxed max-w-4xl">
                The <strong>Classification of Finite Simple Groups</strong> (completed circa 2004) is one of the most monumental collaborative achievements in the history of mathematics. It definitively proves that every "atom" of symmetry belongs to one of four distinct families:
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
                <FamilyCard title="Cyclic" symbol="{\mathbb{Z}_p}" desc="Prime order groups." color="bg-emerald-500 text-emerald-900" count="Infinite" />
                <FamilyCard title="Alternating" symbol="{A_n}" desc="Even permutations." color="bg-teal-500 text-teal-900" count="Infinite" />
                <FamilyCard title="Lie Type" symbol="{G(q)}" desc="Matrix-based groups." color="bg-cyan-500 text-cyan-900" count="16 Families" />
                <FamilyCard title="Sporadic" symbol="{S}" desc="The strange outliers." color="bg-purple-500 text-purple-900" count="26 Groups" />
            </div>

            {/* THE MONSTER HERO BLOCK */}
            <div className="rounded-3xl bg-gradient-to-br from-purple-900/40 to-black/80 border border-purple-500/30 p-8 md:p-16 relative overflow-hidden shadow-2xl backdrop-blur-xl flex flex-col lg:flex-row items-center gap-12">
                <div className="absolute -right-20 -top-20 opacity-10 pointer-events-none">
                    <Crown size={400} className="text-purple-300" />
                </div>

                <div className="flex-1 relative z-10">
                    <h2 className="text-5xl md:text-6xl font-black text-white mb-6 tracking-tighter">
                        The Monster <M>{"\\mathbb{M}"}</M>
                    </h2>
                    <p className="text-lg text-purple-200/80 mb-8 leading-relaxed">
                        The absolute largest of the 26 sporadic groups. A diamond of impossible geometric complexity existing intrinsically in 196,883 dimensions.
                    </p>
                    
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                        <div className="p-6 rounded-2xl bg-black/60 border border-purple-500/30 shadow-inner">
                            <div className="text-[10px] uppercase tracking-widest text-purple-400 font-bold mb-3">Total Order</div>
                            <div className="text-white font-mono"><M>{"\\approx 8 \\times 10^{53}"}</M></div>
                        </div>
                        <div className="p-6 rounded-2xl bg-black/60 border border-purple-500/30 shadow-inner">
                            <div className="text-[10px] uppercase tracking-widest text-purple-400 font-bold mb-3">Monstrous Moonshine</div>
                            <div className="text-white font-mono text-sm leading-relaxed">Links to Modular Function <M>j(\tau)</M></div>
                        </div>
                    </div>
                </div>

                <div className="w-full lg:w-1/3 flex justify-center relative z-10">
                    [Image of the Griess algebra or Monster group geometric representation]
                </div>
            </div>
        </section>

      </div>
    </main>
  );
}

// --- HELPER COMPONENTS ---

function DefinitionCard({ term, def, icon: Icon, color }: any) {
    return (
        <div className="p-6 rounded-3xl bg-black/40 border border-white/10 hover:border-white/20 transition-colors shadow-inner">
            <div className={`flex items-center gap-3 mb-4 ${color}`}>
                <Icon size={24} />
                <h3 className="font-bold uppercase tracking-widest text-sm">{term}</h3>
            </div>
            <p className="text-sm text-zinc-400 leading-relaxed">
                {def}
            </p>
        </div>
    );
}

function FamilyCard({ title, symbol, desc, color, count }: any) {
    return (
        <div className="p-6 rounded-3xl bg-black/40 border border-white/10 hover:border-white/20 transition-all group shadow-inner flex flex-col">
            <div className="flex justify-between items-start mb-6">
                <div className={`px-4 py-2 rounded-xl ${color} flex items-center justify-center font-bold shadow-[0_0_15px_rgba(255,255,255,0.2)] text-base`}>
                    <M>{symbol}</M>
                </div>
            </div>
            <h3 className="font-bold text-white text-lg mb-2 group-hover:text-emerald-400 transition-colors">{title}</h3>
            <p className="text-sm text-zinc-400 leading-relaxed mb-6 flex-1">{desc}</p>
            <div className="mt-auto border-t border-white/10 pt-4">
                <span className="text-[10px] font-mono font-bold text-zinc-500 uppercase tracking-widest">{count}</span>
            </div>
        </div>
    );
}