"use client";

import { useState } from "react";
import Link from "next/link";
import DiscreteBackground from "@/components/DiscreteBackground"; 
import ModularClockWidget from "@/components/ModularClockWidget";
import LagrangeWidget from "@/components/LagrangeWidget";
import { 
  Grid, Circle, Shuffle, Crown, Hash, Layers, 
  BookOpen, ChevronRight, Binary, LayoutGrid, ArrowRight,
  ShieldCheck, Globe, Key, User
} from "lucide-react";

// --- NAVIGATION DATA ---
const CHAPTERS = [
  { id: "intro", title: "1.0 Definition" },
  { id: "cyclic", title: "2.0 Cyclic Groups" },
  { id: "symmetric", title: "3.0 Permutations" },
  { id: "structure", title: "4.0 Structure" },
  { id: "classification", title: "5.0 The Periodic Table" },
  { id: "monster", title: "6.0 The Monster" },
];

export default function FiniteGroupsPage() {
  const [activeChapter, setActiveChapter] = useState("intro");

  const scrollTo = (id: string) => {
    setActiveChapter(id);
    document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  return (
    <main className="relative min-h-screen w-full overflow-hidden bg-[#020617] text-white selection:bg-cyan-500/30 font-sans">
      
      {/* 1. Background */}
      <DiscreteBackground /> 
      
      <div className="relative z-10 w-full min-h-screen flex flex-col lg:flex-row max-w-[1600px] mx-auto">
        

        {/* --- MAIN CONTENT AREA --- */}
        <div className="flex-1 lg:ml-64 grid grid-cols-1 xl:grid-cols-12 gap-12 p-6 md:p-12 lg:p-16">
            
            {/* --- COLUMN 1: NARRATIVE (8 Cols) --- */}
            <div className="xl:col-span-8 space-y-24">
                
                {/* 1. INTRODUCTION */}
                <section id="intro" className="scroll-mt-32">
                    <header className="mb-12">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-900/30 border border-cyan-500/30 text-cyan-400 text-[10px] font-bold uppercase tracking-widest mb-6">
                            <Binary size={12} /> Discrete Mathematics
                        </div>
                        <h1 className="text-6xl md:text-8xl font-black tracking-tighter text-white mb-6">
                            Finite Groups
                        </h1>
                        <p className="text-xl text-neutral-300 font-light leading-relaxed">
                            The study of symmetries with limits. Unlike continuous groups (like the rotation of a circle), finite groups have a countable number of elements. They are the "pixels" of mathematical structure.
                        </p>
                    </header>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <DefinitionCard 
                            term="Order |G|" 
                            def="The number of elements in a group. If |G| is finite, G is a finite group."
                            icon={Hash}
                        />
                        <DefinitionCard 
                            term="Simple Group" 
                            def="A group that has no non-trivial normal subgroups. These are the 'prime numbers' of group theory."
                            icon={Crown}
                        />
                    </div>
                </section>

                {/* 2. CYCLIC GROUPS */}
                <section id="cyclic" className="scroll-mt-32 border-t border-white/5 pt-12">
                    <h2 className="text-3xl font-black text-white mb-6 flex items-center gap-3">
                        <Circle className="text-cyan-400" /> 2.0 Cyclic Groups
                    </h2>
                    <p className="text-neutral-400 leading-relaxed mb-6">
                        The simplest finite groups. Generated by a single element repeating itself until it returns to the start. Think of a clock face: $12 + 1 = 1$.
                    </p>
                    
                    <div className="bg-black/40 p-6 rounded-2xl border border-white/10 font-mono text-sm mb-8">
                        <div className="flex items-center gap-4 border-b border-white/10 pb-4 mb-4">
                            <span className="text-cyan-400 font-bold">Z₄</span>
                            <span className="text-neutral-500">Integers Modulo 4</span>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <span className="text-[10px] text-neutral-500 uppercase block mb-1">Set</span>
                                <span className="text-white">&#123;0, 1, 2, 3&#125;</span>
                            </div>
                            <div>
                                <span className="text-[10px] text-neutral-500 uppercase block mb-1">Generator</span>
                                <span className="text-white">⟨1⟩</span>
                            </div>
                        </div>
                    </div>

                    <h3 className="text-lg font-bold text-white mb-3">Applications</h3>
                    <ul className="space-y-3">
                        <AppItem icon={Key} title="Cryptography" desc="RSA encryption relies on the properties of cyclic groups formed by large primes." />
                        <AppItem icon={Globe} title="Signal Processing" desc="Roots of unity (cyclic groups) form the basis of the Discrete Fourier Transform." />
                    </ul>
                </section>

                {/* 3. SYMMETRIC GROUPS */}
                <section id="symmetric" className="scroll-mt-32 border-t border-white/5 pt-12">
                    <h2 className="text-3xl font-black text-white mb-6 flex items-center gap-3">
                        <Shuffle className="text-pink-400" /> 3.0 Permutations
                    </h2>
                    <p className="text-neutral-400 leading-relaxed mb-6">
                        The Symmetric Group $S_n$ consists of all possible shuffles of $n$ distinct items. It is the "Mother Group"—Cayley's Theorem proves that every finite group lives inside a Symmetric Group.
                    </p>

                    <div className="p-6 rounded-2xl bg-neutral-900/50 border border-white/10 mb-8">
                        <h4 className="text-xs font-bold uppercase text-neutral-500 mb-4">Cycle Notation Example</h4>
                        <div className="flex items-center gap-8">
                            <div className="text-3xl font-mono text-white">(1 2 3)</div>
                            <ArrowRight className="text-pink-500" />
                            <div className="text-sm text-neutral-300">
                                1 goes to 2 <br/>
                                2 goes to 3 <br/>
                                3 goes to 1
                            </div>
                        </div>
                    </div>

                    <h3 className="text-lg font-bold text-white mb-3">Real World: The Rubik's Cube</h3>
                    <p className="text-sm text-neutral-400 leading-relaxed mb-4">
                        A Rubik's cube is a physical representation of a subgroup of $S_{48}$. Every turn is a permutation. Solving it means finding the inverse operation to return to Identity.
                    </p>
                </section>

                {/* 4. STRUCTURE */}
                <section id="structure" className="scroll-mt-32 border-t border-white/5 pt-12">
                    <h2 className="text-3xl font-black text-white mb-6 flex items-center gap-3">
                        <Layers className="text-amber-400" /> 4.0 Structure
                    </h2>
                    <p className="text-neutral-400 leading-relaxed mb-6">
                        Groups are not just bags of elements; they have rigid internal architecture. 
                    </p>
                    <div className="p-6 border-l-4 border-amber-500 bg-amber-900/10 rounded-r-xl mb-8">
                        <h3 className="text-lg font-bold text-amber-100 mb-2">Lagrange's Theorem</h3>
                        <p className="text-sm text-amber-200/80 italic">
                            "If G is a finite group and H is a subgroup of G, then the order of H divides the order of G."
                        </p>
                    </div>
                    <p className="text-sm text-neutral-400">
                        This is a powerful constraint. It means a group of size 12 *cannot* have a subgroup of size 5. It forces symmetry to be quantized.
                    </p>
                </section>

                {/* 5. CLASSIFICATION */}
                <section id="classification" className="scroll-mt-32 border-t border-white/5 pt-12">
                    <h2 className="text-3xl font-black text-white mb-6 flex items-center gap-3">
                        <LayoutGrid className="text-emerald-400" /> 5.0 The Periodic Table
                    </h2>
                    
                    <p className="text-neutral-400 mb-8">
                        The <strong>Classification of Finite Simple Groups</strong> (completed ~2004) is one of the monumental achievements of math. It states that every "atom" of symmetry belongs to one of four families:
                    </p>

                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <FamilyCard title="Cyclic" symbol="Zp" desc="Prime order groups." color="bg-emerald-500" count="Infinite" />
                        <FamilyCard title="Alternating" symbol="An" desc="Even permutations." color="bg-teal-500" count="Infinite" />
                        <FamilyCard title="Lie Type" symbol="G(q)" desc="Matrix groups." color="bg-cyan-500" count="16 Families" />
                        <FamilyCard title="Sporadic" symbol="M" desc="The 26 outliers." color="bg-purple-500" count="26 Groups" />
                    </div>
                </section>

                {/* 6. THE MONSTER */}
                <section id="monster" className="scroll-mt-32 border-t border-white/5 pt-12 pb-20">
                    <div className="rounded-3xl bg-gradient-to-br from-purple-900/30 to-black border border-purple-500/30 p-10 relative overflow-hidden">
                        <div className="relative z-10">
                            <Crown size={48} className="text-purple-400 mb-6" />
                            <h2 className="text-5xl font-black text-white mb-4">The Monster</h2>
                            <p className="text-lg text-purple-200/60 mb-8 max-w-xl">
                                The largest sporadic group. A diamond of impossible complexity existing in 196,883 dimensions.
                            </p>
                            
                            <div className="grid grid-cols-2 gap-4 max-w-lg">
                                <div className="p-4 rounded bg-black/40 border border-purple-500/20">
                                    <div className="text-[10px] uppercase text-purple-500 font-bold">Order</div>
                                    <div className="text-white font-mono text-lg">~8x10⁵³</div>
                                </div>
                                <div className="p-4 rounded bg-black/40 border border-purple-500/20">
                                    <div className="text-[10px] uppercase text-purple-500 font-bold">Moonshine</div>
                                    <div className="text-white font-mono text-lg">j(τ) Link</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>

            {/* --- COLUMN 2: THE SIDEBAR LAB (4 Cols) --- */}
            <div className="xl:col-span-4 space-y-8">
                
                {/* WIDGET 1: CLOCK */}
                <div className="sticky top-8 space-y-8">
                    <div className="rounded-3xl border border-white/10 bg-[#020617]/80 backdrop-blur-xl overflow-hidden shadow-2xl">
                        <div className="bg-white/5 p-4 border-b border-white/5 flex justify-between items-center">
                            <span className="text-xs font-bold text-white uppercase tracking-wider">Lab: Modulo</span>
                            <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
                        </div>
                        <div className="p-6">
                            <ModularClockWidget />
                        </div>
                    </div>

                    {/* WIDGET 2: LAGRANGE */}
                    <div className="rounded-3xl border border-white/10 bg-[#020617]/80 backdrop-blur-xl overflow-hidden shadow-2xl">
                        <div className="bg-white/5 p-4 border-b border-white/5 flex justify-between items-center">
                            <span className="text-xs font-bold text-white uppercase tracking-wider">Lab: Tiling</span>
                            <div className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
                        </div>
                        <div className="p-6">
                            <LagrangeWidget />
                        </div>
                    </div>

                    {/* WIDGET 3: DID YOU KNOW? */}
                    <div className="p-6 rounded-3xl bg-indigo-900/20 border border-indigo-500/20">
                        <div className="flex items-center gap-2 mb-3 text-indigo-400">
                            <User size={16} />
                            <span className="text-xs font-bold uppercase">Évariste Galois</span>
                        </div>
                        <p className="text-xs text-indigo-200/70 leading-relaxed">
                            He invented Group Theory as a teenager to prove that 5th-degree polynomials are unsolvable. He died in a duel at age 20, sketching his theories the night before.
                        </p>
                    </div>

                </div>

            </div>

        </div>
      </div>
    </main>
  );
}

// --- HELPER COMPONENTS ---

function DefinitionCard({ term, def, icon: Icon }: any) {
    return (
        <div className="p-6 rounded-2xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors">
            <div className="flex items-center gap-3 mb-3 text-cyan-300">
                <Icon size={20} />
                <h3 className="font-bold uppercase tracking-wider text-sm">{term}</h3>
            </div>
            <p className="text-sm text-neutral-400 leading-relaxed">
                {def}
            </p>
        </div>
    );
}

function AppItem({ icon: Icon, title, desc }: any) {
    return (
        <li className="flex gap-4 p-4 rounded-xl bg-white/5 border border-white/5">
            <div className="mt-1 text-cyan-400"><Icon size={16} /></div>
            <div>
                <h4 className="text-sm font-bold text-white">{title}</h4>
                <p className="text-xs text-neutral-400 mt-1 leading-relaxed">{desc}</p>
            </div>
        </li>
    );
}

function FamilyCard({ title, symbol, desc, color, count }: any) {
    return (
        <div className="p-5 rounded-xl bg-black/40 border border-white/10 hover:border-white/20 transition-all group">
            <div className="flex justify-between items-start mb-3">
                <div className={`w-8 h-8 rounded-lg ${color} flex items-center justify-center font-bold text-black shadow-lg text-xs`}>
                    {symbol}
                </div>
                <span className="text-[9px] font-mono text-neutral-500 uppercase">{count}</span>
            </div>
            <h3 className="font-bold text-white text-sm mb-1 group-hover:text-cyan-400 transition-colors">{title}</h3>
            <p className="text-[10px] text-neutral-400">{desc}</p>
        </div>
    );
}