"use client";

import { useState } from "react";
import Link from "next/link";
import DomainPageHeader from "@/app/_components/DomainPageHeader";
import { M } from "@/app/_components/Math";
import WaveField from "../_components/WaveField";
import { ArrowRight, Focus, Glasses, Route } from "lucide-react";

export default function LensesImagingPage() {
  const [focalLength, setFocalLength] = useState(2);
  const [objectDistance, setObjectDistance] = useState(3.5);
  const [objectHeight, setObjectHeight] = useState(1);
  const [answer, setAnswer] = useState<string | null>(null);

  const invImageDistance = 1 / focalLength - 1 / objectDistance;
  const imageDistance = Math.abs(invImageDistance) < 1e-4 ? Number.POSITIVE_INFINITY : 1 / invImageDistance;
  const magnification = Number.isFinite(imageDistance) ? -imageDistance / objectDistance : Number.NEGATIVE_INFINITY;
  const imageHeight = Number.isFinite(magnification) ? objectHeight * magnification : Number.NEGATIVE_INFINITY;
  const real = imageDistance > 0;
  const insideFocus = objectDistance < focalLength;

  return (
    <main className="relative min-h-screen overflow-x-hidden bg-[#061008] text-slate-100 selection:bg-green-300/25">
      <WaveField mode="lenses" intensity={1.25} />
      <div className="relative z-10 mx-auto w-full max-w-[1400px] px-4 pb-12 sm:px-6 xl:px-8">
        <div className="sticky top-0 z-30 -mx-4 border-b border-white/[0.07] bg-[#061008]/68 px-4 pb-4 pt-5 backdrop-blur-2xl sm:-mx-6 sm:px-6 xl:-mx-8 xl:px-8">
          <DomainPageHeader breadcrumbs={[{ label: "Physics", href: "/natural-science/physics" }, { label: "Waves & Optics", href: "/natural-science/physics/waves-optics" }, { label: "Lenses & Imaging" }]} eyebrow="Waves & Optics · 05 / 06" icon={Glasses} title={<span>Lenses & Imaging</span>} subtitle="A lens redirects many rays from each object point. Where those rays converge—or appear to diverge from—determines the image position, orientation, and size." accentRgb="74, 222, 128" titleClassName="font-mono text-[clamp(2rem,4.3vw,4.5rem)] font-semibold uppercase leading-[0.9] tracking-[-0.052em] text-[#f3fff6]" headerClassName="border-transparent" />
        </div>

        <section className="mt-5 grid gap-4 rounded-[28px] border border-green-200/[0.10] bg-black/[0.08] p-5 backdrop-blur-md lg:grid-cols-[minmax(0,1fr)_minmax(300px,0.72fr)] sm:p-6">
          <div><div className="text-[10px] font-semibold uppercase tracking-[0.15em] text-green-300/70">The learner question</div><h2 className="mt-2 text-[clamp(1.6rem,3vw,2.35rem)] font-semibold tracking-[-0.04em] text-white">How can curved glass create an image somewhere else in space?</h2><p className="mt-3 max-w-3xl text-[13px] leading-6 text-slate-400">Each small region of the lens refracts light. The lens shape organizes those direction changes so rays from one object point either meet again or leave with directions that appear to come from a common point.</p></div>
          <div className="rounded-[18px] border border-green-200/[0.09] bg-green-400/[0.025] p-4"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-green-300/62">Thin-lens relationships</div><div className="mt-3 space-y-2 text-[18px] text-white"><M>{"\\frac1f=\\frac1{d_o}+\\frac1{d_i}"}</M><br /><M>{"m=-\\frac{d_i}{d_o}=\\frac{h_i}{h_o}"}</M></div><p className="mt-2 text-[11px] leading-5 text-slate-500">This page uses a converging thin lens and the usual real-is-positive sign convention for image distance.</p></div>
        </section>

        <section className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(320px,0.8fr)]">
          <div className="rounded-[30px] border border-white/[0.08] bg-black/[0.07] p-5 backdrop-blur-sm sm:p-6">
            <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[9px] font-semibold uppercase tracking-[0.14em] text-green-300/70">Ray-construction lab</div><h2 className="mt-1 text-[21px] font-semibold tracking-[-0.025em] text-white">Move the object through the focal region.</h2></div><div className="rounded-full border border-white/[0.07] bg-black/[0.16] px-3 py-1.5 font-mono text-[10px] text-slate-500">{insideFocus ? "inside focal length" : real ? "real image" : "virtual image"}</div></div>
            <div className="relative mt-4 min-h-[410px] overflow-hidden rounded-[24px] border border-white/[0.07] bg-[#0b130c]/64 p-5"><LensDiagram focalLength={focalLength} objectDistance={objectDistance} objectHeight={objectHeight} imageDistance={imageDistance} imageHeight={imageHeight} real={real} /><div className="absolute bottom-5 left-5 right-5 grid grid-cols-4 gap-2"><Readout label="dₒ" value={`${objectDistance.toFixed(2)} m`} rgb="250, 204, 21" /><Readout label="dᵢ" value={Number.isFinite(imageDistance) ? `${imageDistance.toFixed(2)} m` : "∞"} rgb="34, 211, 238" /><Readout label="magnification" value={Number.isFinite(magnification) ? magnification.toFixed(2) : "∞"} rgb="74, 222, 128" /><Readout label="image" value={Number.isFinite(imageDistance) ? `${real ? "real" : "virtual"}, ${magnification < 0 ? "inverted" : "upright"}` : "at infinity"} rgb="232, 121, 249" /></div></div>
            <div className="mt-5 grid gap-5 sm:grid-cols-3"><Control label="Focal length f" value={focalLength} min={1} max={4} step={0.05} unit="m" onChange={setFocalLength} /><Control label="Object distance dₒ" value={objectDistance} min={0.7} max={7} step={0.05} unit="m" onChange={setObjectDistance} /><Control label="Object height hₒ" value={objectHeight} min={0.4} max={1.8} step={0.05} unit="m" onChange={setObjectHeight} /></div>
          </div>
          <div className="space-y-4"><Insight icon={Focus} title="Outside the focal length" text="For a converging lens with dₒ > f, outgoing rays can actually meet on the far side, producing a real inverted image." rgb="34, 211, 238" /><Insight icon={Glasses} title="Inside the focal length" text="When dₒ < f, outgoing rays diverge. Tracing them backward produces an upright virtual image on the object side—the magnifying-glass regime." rgb="74, 222, 128" /><Insight icon={Route} title="Principal rays are construction shortcuts" text="The familiar parallel, focal, and central rays are selected representatives of a much larger family of refracted rays from the same object point." rgb="250, 204, 21" /></div>
        </section>

        <section className="mt-4 grid gap-3 md:grid-cols-3"><Principle title="At dₒ = f" text="The outgoing rays are parallel in the ideal thin-lens model, so the image is described as being at infinity." rgb="74, 222, 128" /><Principle title="Magnification includes orientation" text="Negative magnification means the image is inverted relative to the object; positive magnification means upright." rgb="232, 121, 249" /><Principle title="Imaging is reversible" text="Light paths through passive optical systems are reversible, so object and image roles can often be exchanged geometrically." rgb="34, 211, 238" /></section>

        <section className="mt-4 rounded-[26px] border border-white/[0.08] bg-black/[0.08] p-5 backdrop-blur-md sm:p-6"><div className="text-[9px] font-semibold uppercase tracking-[0.14em] text-emerald-300/65">Transfer check</div><h2 className="mt-1 text-[20px] font-semibold text-white">An object is placed inside the focal length of a converging lens. What kind of image appears?</h2><div className="mt-4 flex flex-wrap gap-2">{["real and inverted", "virtual and upright", "no optical image at all"].map((option) => <button key={option} type="button" onClick={() => setAnswer(option)} className="rounded-full border px-4 py-2 text-[11px]" style={{ borderColor: answer === option ? "rgba(45,212,191,0.34)" : "rgba(255,255,255,0.07)", background: answer === option ? "rgba(45,212,191,0.05)" : "rgba(0,0,0,0.12)", color: answer === option ? "rgb(209,250,229)" : "rgb(148,163,184)" }}>{option}</button>)}</div>{answer ? <div className={`mt-4 rounded-[16px] border p-4 ${answer === "virtual and upright" ? "border-emerald-300/[0.16] bg-emerald-400/[0.03]" : "border-amber-300/[0.16] bg-amber-400/[0.025]"}`}><strong className={`text-[11px] ${answer === "virtual and upright" ? "text-emerald-200" : "text-amber-200"}`}>{answer === "virtual and upright" ? "Exactly" : "Trace the outgoing rays backward"}</strong><p className="mt-1 text-[11px] leading-5 text-slate-500">Inside the focal length, the transmitted rays diverge and appear to come from an enlarged upright point on the object side.</p></div> : null}<div className="mt-5 flex justify-between"><Link href="/natural-science/physics/waves-optics/diffraction" className="text-[10px] text-slate-500 hover:text-slate-300">← Diffraction</Link><div className="inline-flex items-center gap-2 rounded-full border border-fuchsia-200/[0.08] bg-fuchsia-400/[0.02] px-4 py-2 text-[10px] text-slate-600">Next: Standing Waves & Resonance · planned <ArrowRight size={12} /></div></div></section>
      </div>
    </main>
  );
}

function LensDiagram({ focalLength, objectDistance, objectHeight, imageDistance, imageHeight, real }: { focalLength: number; objectDistance: number; objectHeight: number; imageDistance: number; imageHeight: number; real: boolean }) { const width=760; const axisY=160; const lensX=380; const scale=55; const objX=Math.max(50,lensX-objectDistance*scale); const objTop=axisY-objectHeight*55; const focusOffset=focalLength*scale; const finite=Number.isFinite(imageDistance); const imgX=finite?Math.max(30,Math.min(730,lensX+imageDistance*scale)):740; const imgTop=finite?axisY-imageHeight*55:axisY; const focalRight=lensX+focusOffset; const focalLeft=lensX-focusOffset; return <svg viewBox={`0 0 ${width} 320`} className="absolute inset-x-5 top-5 h-[320px] w-[calc(100%-2.5rem)]" preserveAspectRatio="none" role="img" aria-label="Thin lens ray diagram"><line x1="20" x2="740" y1={axisY} y2={axisY} stroke="rgba(148,163,184,0.14)" /><ellipse cx={lensX} cy={axisY} rx="18" ry="125" fill="rgba(186,230,253,0.045)" stroke="rgba(186,230,253,0.32)" strokeWidth="2" /><circle cx={focalLeft} cy={axisY} r="4" fill="rgb(250,204,21)" /><circle cx={focalRight} cy={axisY} r="4" fill="rgb(250,204,21)" /><text x={focalLeft-8} y={axisY+20} fill="rgba(250,204,21,0.60)" fontSize="9">F</text><text x={focalRight-8} y={axisY+20} fill="rgba(250,204,21,0.60)" fontSize="9">F</text><line x1={objX} x2={objX} y1={axisY} y2={objTop} stroke="rgb(250,204,21)" strokeWidth="4" /><path d={`M ${objX-5},${objTop+8} L ${objX},${objTop} L ${objX+5},${objTop+8}`} fill="none" stroke="rgb(250,204,21)" strokeWidth="3" /><line x1={objX} y1={objTop} x2={lensX} y2={objTop} stroke="rgb(34,211,238)" strokeWidth="2" />{finite?<line x1={lensX} y1={objTop} x2={imgX} y2={imgTop} stroke="rgb(34,211,238)" strokeWidth="2" />:null}<line x1={objX} y1={objTop} x2={lensX} y2={axisY} stroke="rgba(74,222,128,0.78)" strokeWidth="2" />{finite?<line x1={lensX} y1={axisY} x2={imgX} y2={imgTop} stroke="rgba(74,222,128,0.78)" strokeWidth="2" />:null}{finite?<><line x1={imgX} x2={imgX} y1={axisY} y2={imgTop} stroke={real?"rgb(232,121,249)":"rgba(232,121,249,0.58)"} strokeWidth="4" strokeDasharray={real?undefined:"5 5"} /><path d={`M ${imgX-5},${imgTop+(imageHeight>=0?8:-8)} L ${imgX},${imgTop} L ${imgX+5},${imgTop+(imageHeight>=0?8:-8)}`} fill="none" stroke="rgb(232,121,249)" strokeWidth="3" />{!real?<><line x1={lensX} y1={objTop} x2={imgX} y2={imgTop} stroke="rgba(232,121,249,0.30)" strokeDasharray="5 5" /><line x1={lensX} y1={axisY} x2={imgX} y2={imgTop} stroke="rgba(232,121,249,0.30)" strokeDasharray="5 5" /></>:null}</>:<text x="610" y="70" fill="rgba(74,222,128,0.65)" fontSize="10">outgoing rays parallel</text>}</svg>; }
function Control({ label, value, min, max, step, unit, onChange }: { label: string; value: number; min: number; max: number; step: number; unit: string; onChange: (value: number) => void }) { return <div><div className="mb-2 flex justify-between text-[9px] uppercase tracking-[0.11em] text-slate-600"><span>{label}</span><span className="font-mono text-green-100/60">{value.toFixed(2)} {unit}</span></div><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="h-1.5 w-full cursor-pointer appearance-none rounded-full bg-slate-800 accent-green-400" /></div>; }
function Readout({ label, value, rgb }: { label: string; value: string; rgb: string }) { return <div className="rounded-[13px] border border-white/[0.06] bg-black/[0.20] px-3 py-2.5"><div className="text-[8px] uppercase tracking-[0.1em] text-slate-600">{label}</div><div className="mt-1 truncate font-mono text-[10px]" style={{ color: `rgba(${rgb},0.78)` }}>{value}</div></div>; }
function Insight({ icon: Icon, title, text, rgb }: { icon: typeof Glasses; title: string; text: string; rgb: string }) { return <div className="rounded-[22px] border border-white/[0.07] bg-black/[0.08] p-4 backdrop-blur-md"><div className="flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[0.12em]" style={{ color: `rgba(${rgb},0.68)` }}><Icon size={12} /> imaging idea</div><strong className="mt-2 block text-[12px] text-white">{title}</strong><p className="mt-2 text-[11px] leading-5 text-slate-500">{text}</p></div>; }
function Principle({ title, text, rgb }: { title: string; text: string; rgb: string }) { return <div className="rounded-[18px] border border-white/[0.06] bg-black/[0.08] p-4"><div className="h-1 w-10 rounded-full" style={{ background: `rgba(${rgb},0.72)` }} /><strong className="mt-3 block text-[12px] text-white">{title}</strong><p className="mt-2 text-[11px] leading-5 text-slate-500">{text}</p></div>; }
