"use client";

import { useMemo, useState } from "react";
import { CloudRain, Droplets, Gauge, Waves, type LucideIcon } from "lucide-react";

export default function WaterBudgetLab() {
  const [precipitation, setPrecipitation] = useState(100);
  const [evapotranspiration, setEvapotranspiration] = useState(48);
  const [runoff, setRunoff] = useState(32);
  const storageChange = useMemo(() => precipitation - evapotranspiration - runoff, [precipitation, evapotranspiration, runoff]);
  const storageLabel = storageChange > 0 ? "storage increases" : storageChange < 0 ? "storage decreases" : "steady storage";
  const storageRgb = storageChange > 0 ? "52, 211, 153" : storageChange < 0 ? "248, 113, 113" : "125, 211, 252";

  return <section className="overflow-hidden rounded-[30px] border border-sky-200/[0.12] bg-black/[0.18] backdrop-blur-xl">
    <div className="grid border-b border-white/[0.07] lg:grid-cols-[minmax(0,1fr)_380px]"><div className="px-5 py-5 sm:px-6"><div className="flex items-center gap-2 font-mono text-[9px] font-semibold uppercase tracking-[0.15em] text-sky-200/62"><Gauge size={13}/> Watershed budget lab</div><h2 className="mt-2 text-[clamp(1.8rem,3.2vw,3rem)] font-semibold tracking-[-0.047em] text-white">Track water by balancing inputs, outputs, and storage.</h2><p className="mt-2 max-w-3xl text-[12px] leading-6 text-slate-400">For a chosen watershed and time interval, precipitation enters the budget. Evapotranspiration and runoff leave it. The remainder changes storage in soil, groundwater, lakes, snow, or other reservoirs.</p></div><div className="border-t border-white/[0.07] p-5 lg:border-l lg:border-t-0"><div className="font-mono text-[8px] uppercase tracking-[0.12em] text-slate-600">Budget equation</div><div className="mt-3 font-mono text-[20px] font-semibold text-sky-100/82">P = ET + Q + ΔS</div><p className="mt-2 text-[10px] leading-5 text-slate-600">This simplified form hides many sub-fluxes, but the accounting principle is the backbone of hydrology.</p></div></div>
    <div className="grid lg:grid-cols-[minmax(0,1fr)_390px]"><div className="border-b border-white/[0.07] p-5 sm:p-6 lg:border-b-0 lg:border-r"><BudgetSlider icon={CloudRain} label="Precipitation (P)" value={precipitation} min={40} max={160} onChange={setPrecipitation} rgb="96, 165, 250"/><BudgetSlider icon={Droplets} label="Evapotranspiration (ET)" value={evapotranspiration} min={10} max={100} onChange={setEvapotranspiration} rgb="45, 212, 191"/><BudgetSlider icon={Waves} label="Runoff / discharge (Q)" value={runoff} min={5} max={100} onChange={setRunoff} rgb="34, 211, 238"/></div><div className="p-5 sm:p-6"><div className="font-mono text-[8px] uppercase tracking-[0.12em] text-slate-600">Derived storage change</div><div className="mt-3 text-[44px] font-semibold tracking-[-0.06em]" style={{color:`rgb(${storageRgb})`}}>{storageChange>0?"+":""}{storageChange}</div><div className="font-mono text-[9px] uppercase tracking-[0.12em]" style={{color:`rgba(${storageRgb},0.68)`}}>{storageLabel}</div><div className="mt-6 h-4 overflow-hidden rounded-full bg-white/[0.04]"><div className="h-full transition-[width] duration-300" style={{width:`${Math.min(100,Math.max(0,((storageChange+100)/200)*100))}%`,background:`rgba(${storageRgb},0.65)`}}/></div><div className="mt-2 flex justify-between font-mono text-[7px] uppercase text-slate-700"><span>depletion</span><span>balance</span><span>recharge</span></div><div className="mt-6 rounded-[16px] border border-white/[0.06] bg-black/[0.12] p-4"><div className="font-mono text-[8px] uppercase tracking-[0.1em] text-slate-600">Interpretation</div><p className="mt-2 text-[10px] leading-5 text-slate-500">A positive ΔS can mean aquifer recharge, wetter soil, rising lake levels, or accumulating snow. A negative ΔS means stored water is being drawn down. Which reservoir changes depends on the watershed and season.</p></div></div></div>
  </section>;
}

function BudgetSlider({icon:Icon,label,value,min,max,onChange,rgb}:{icon:LucideIcon;label:string;value:number;min:number;max:number;onChange:(value:number)=>void;rgb:string}) { return <div className="border-b border-white/[0.06] py-5 first:pt-0 last:border-b-0 last:pb-0"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-[12px] border" style={{color:`rgb(${rgb})`,borderColor:`rgba(${rgb},0.22)`,background:`rgba(${rgb},0.035)`}}><Icon size={14}/></span><span className="text-[11px] font-semibold text-white/82">{label}</span></div><span className="font-mono text-[12px]" style={{color:`rgba(${rgb},0.72)`}}>{value}</span></div><input aria-label={label} type="range" min={min} max={max} value={value} onChange={event=>onChange(Number(event.target.value))} className="mt-4 w-full accent-sky-400"/><div className="mt-1 flex justify-between font-mono text-[7px] text-slate-700"><span>{min}</span><span>{max}</span></div></div>; }
